
    insert into ciudad (ciudad) values ("TERMAS DEL DAYMAN");
    insert into ciudad (ciudad) values ("PUNTA RUBIA");
    insert into ciudad (ciudad) values ("18 DE JULIO");
    insert into ciudad (ciudad) values ("PUEBLO NUEVO");
    insert into ciudad (ciudad) values ("18 DE JULIO");
    insert into ciudad (ciudad) values ("BARRA DE CARRASCO");
    insert into ciudad (ciudad) values ("BARRIO HIPODROMO");
    insert into ciudad (ciudad) values ("BARRIO PEREIRA");
    insert into ciudad (ciudad) values ("CANTERAS DE MARELLI");
    insert into ciudad (ciudad) values ("CERROS DE LA CALERA");
    insert into ciudad (ciudad) values ("CIUDAD DE LA COSTA");
    insert into ciudad (ciudad) values ("COLONIA DEL SACRAMENTO");
    insert into ciudad (ciudad) values ("DELTA DEL TIGRE Y VILLAS");
    insert into ciudad (ciudad) values ("DELTA EL TIGRE");
    insert into ciudad (ciudad) values ("LA ESTANZUELA");
    insert into ciudad (ciudad) values ("PASO CAMPAMENTO");
    insert into ciudad (ciudad) values ("RINCON DE PACHECO");
    insert into ciudad (ciudad) values ("TOPADOR");
    insert into ciudad (ciudad) values ("FARO JOSE IGNACIO");
    insert into ciudad (ciudad) values ("FARO JOSE IGNACIO NORTE");
    insert into ciudad (ciudad) values ("PLAYA FOMENTO");
    insert into ciudad (ciudad) values ("GIL");
    insert into ciudad (ciudad) values ("PUEBLO GIL");
    insert into ciudad (ciudad) values ("HARAS DEL LAGO");
    insert into ciudad (ciudad) values ("INSTITUTO ADVENTISTA");
    insert into ciudad (ciudad) values ("FRACCIONAMIENTO SOBRE RUTA 74");
    insert into ciudad (ciudad) values ("FRACC. SOBRE RUTA 74");
    insert into ciudad (ciudad) values ("BARROS BLANCOS");
    insert into ciudad (ciudad) values ("CAPITAN J A ARTIGAS");
    insert into ciudad (ciudad) values ("JOSE PEDRO VARELA");
    insert into ciudad (ciudad) values ("ANTONIOPOLIS");
    insert into ciudad (ciudad) values ("ARAMINDA");
    insert into ciudad (ciudad) values ("ATLANTIDA");
    insert into ciudad (ciudad) values ("ATLANTIDA-AGUARAYBA-");
    insert into ciudad (ciudad) values ("LAGO JARDIN DEL BOSQUE");
    insert into ciudad (ciudad) values ("LAGOMAR");
    insert into ciudad (ciudad) values ("LAS CAAS");
    insert into ciudad (ciudad) values ("LAS CAAS");
    insert into ciudad (ciudad) values ("LOS TITANES");
    insert into ciudad (ciudad) values ("PASO DE LAS TOSCAS");
    insert into ciudad (ciudad) values ("PASO DOA ROSA");
    insert into ciudad (ciudad) values ("PLAYA VERDE");
    insert into ciudad (ciudad) values ("MIGUES");
    insert into ciudad (ciudad) values ("BARRANCAS DE LA CORONILLA");
    insert into ciudad (ciudad) values ("BELLO HORIZONTE");
    insert into ciudad (ciudad) values ("BIARRITZ");
    insert into ciudad (ciudad) values ("BELEN");
    insert into ciudad (ciudad) values ("PROGRESO");
    insert into ciudad (ciudad) values ("PUNTA DEL ESTE");
    insert into ciudad (ciudad) values ("RINCON DE CAADA NIETO");
    insert into ciudad (ciudad) values ("ESTACION RODRIGUEZ");
    insert into ciudad (ciudad) values ("SARANDI DEL YI");
    insert into ciudad (ciudad) values ("CARDAL");
    insert into ciudad (ciudad) values ("CASTILLOS");
    insert into ciudad (ciudad) values ("FCIO SANCHEZ");
    insert into ciudad (ciudad) values ("FLORENCIO SANCHEZ");
    insert into ciudad (ciudad) values ("EL CHORRO");
    insert into ciudad (ciudad) values ("EMPALME OLMOS");
    insert into ciudad (ciudad) values ("ESTACION SOUDRIERS");
    insert into ciudad (ciudad) values ("SOUDRIERS");
    insert into ciudad (ciudad) values ("FLORIDA");
    insert into ciudad (ciudad) values ("FORTIN DE SANTA ROSA");
    insert into ciudad (ciudad) values ("FRAILE MUERTO");
    insert into ciudad (ciudad) values ("GREGORIO AZNAREZ");
    insert into ciudad (ciudad) values ("MANANTIALES");
    insert into ciudad (ciudad) values ("MENDOZA CHICO");
    insert into ciudad (ciudad) values ("AGUAS CORRIENTES");
    insert into ciudad (ciudad) values ("RIVERA");
    insert into ciudad (ciudad) values ("JAVIER DE VIANA");
    insert into ciudad (ciudad) values ("CAINZA CAMPO 3");
    insert into ciudad (ciudad) values ("TOMAS GOMENSORO");
    insert into ciudad (ciudad) values ("CEBOLLATI");
    insert into ciudad (ciudad) values ("VILLA HADITA");
    insert into ciudad (ciudad) values ("SALINAS");
    insert into ciudad (ciudad) values ("LAS FLORES");
    insert into ciudad (ciudad) values ("PUEBLO LAS FLORES");
    insert into ciudad (ciudad) values ("LOMAS DE SOLYMAR");
    insert into ciudad (ciudad) values ("BOCA DEL ROSARIO");
    insert into ciudad (ciudad) values ("CUMBRES DE CARRASCO");
    insert into ciudad (ciudad) values ("KIYU - ORDEIG");
    insert into ciudad (ciudad) values ("ORDEIG");
    insert into ciudad (ciudad) values ("VILLA AEROPARQUE");
    insert into ciudad (ciudad) values ("SAN ANTONIO");
    insert into ciudad (ciudad) values ("BARRIO OBRERO");
    insert into ciudad (ciudad) values ("BARRIO LOPEZ BENITEZ");
    insert into ciudad (ciudad) values ("OLMOS");
    insert into ciudad (ciudad) values ("ARTIGAS");
    insert into ciudad (ciudad) values ("SANTA MONICA");
    insert into ciudad (ciudad) values ("ESTACION ATLANTIDA");
    insert into ciudad (ciudad) values ("ESTACION LA FLORESTA");
    insert into ciudad (ciudad) values ("NUEVA PALMIRA");
    insert into ciudad (ciudad) values ("NUEVO BERLIN");
    insert into ciudad (ciudad) values ("OCEAN PARK");
    insert into ciudad (ciudad) values ("CALNU");
    insert into ciudad (ciudad) values ("LAS PIEDRAS");
    insert into ciudad (ciudad) values ("SOFIA SANTOS");
    insert into ciudad (ciudad) values ("PLAYA PASCUAL");
    insert into ciudad (ciudad) values ("RIO BRANCO");
    insert into ciudad (ciudad) values ("FERRER");
    insert into ciudad (ciudad) values ("PUEBLO FERRER");
    insert into ciudad (ciudad) values ("DURAZNO");
    insert into ciudad (ciudad) values ("LORENZO GEYRES");
    insert into ciudad (ciudad) values ("TOLEDO");
    insert into ciudad (ciudad) values ("MINAS");
    insert into ciudad (ciudad) values ("POLANCO NORTE");
    insert into ciudad (ciudad) values ("MASOLLER");
    insert into ciudad (ciudad) values ("MASOLLER");
    insert into ciudad (ciudad) values ("PIRIAPOLIS");
    insert into ciudad (ciudad) values ("CASA BLANCA");
    insert into ciudad (ciudad) values ("ALGORTA");
    insert into ciudad (ciudad) values ("PUNTA BALLENA");
    insert into ciudad (ciudad) values ("NUEVO PAYSANDU");
    insert into ciudad (ciudad) values ("PUEBLO GRECCO");
    insert into ciudad (ciudad) values ("PUEBLO FEDERACION");
    insert into ciudad (ciudad) values ("CUCHILLA DE BURICAYUPI");
    insert into ciudad (ciudad) values ("BARRIO ANGLO");
    insert into ciudad (ciudad) values ("LA PEDRERA");
    insert into ciudad (ciudad) values ("PASO LAPUENTE");
    insert into ciudad (ciudad) values ("CHUY");
    insert into ciudad (ciudad) values ("PINEPARK");
    insert into ciudad (ciudad) values ("PINE PARK");
    insert into ciudad (ciudad) values ("COLOLO TINOSA");
    insert into ciudad (ciudad) values ("PUEBLO CAYETANO");
    insert into ciudad (ciudad) values ("LA BOYADA");
    insert into ciudad (ciudad) values ("CAADA GRANDE");
    insert into ciudad (ciudad) values ("SAN LUIS AL MEDIO");
    insert into ciudad (ciudad) values ("LA CORONILLA");
    insert into ciudad (ciudad) values ("LARES");
    insert into ciudad (ciudad) values ("PASO DE LOS TOROS");
    insert into ciudad (ciudad) values ("PASODE LOSTOROS");
    insert into ciudad (ciudad) values ("ARROCERA SAN FERNANDO");
    insert into ciudad (ciudad) values ("TACUAREMBO");
    insert into ciudad (ciudad) values ("PASO FARIAS");
    insert into ciudad (ciudad) values ("ESTACION MIGUES");
    insert into ciudad (ciudad) values ("VIEJO MOLINO SAN BERNARDO");
    insert into ciudad (ciudad) values ("VIEJO MOLINO Y SAN BERNARDO");
    insert into ciudad (ciudad) values ("RAMON TRIGO");
    insert into ciudad (ciudad) values ("LA CASILLA");
    insert into ciudad (ciudad) values ("AGRACIADA");
    insert into ciudad (ciudad) values ("COLONIA VALDENSE");
    insert into ciudad (ciudad) values ("EL ENSUEO");
    insert into ciudad (ciudad) values ("LA HORQUETA");
    insert into ciudad (ciudad) values ("SAN PEDRO");
    insert into ciudad (ciudad) values ("SANTA REGINA");
    insert into ciudad (ciudad) values ("JUAN JACKSON");
    insert into ciudad (ciudad) values ("BLANQUILLO");
    insert into ciudad (ciudad) values ("PUEBLO DE ALVAREZ");
    insert into ciudad (ciudad) values ("LA CRUZ");
    insert into ciudad (ciudad) values ("PUNTAS DE MACIEL");
    insert into ciudad (ciudad) values ("ESTACION CAPILLA DEL SAUCE");
    insert into ciudad (ciudad) values ("ARAMENDIA");
    insert into ciudad (ciudad) values ("CUCHILLA DE FUEGO");
    insert into ciudad (ciudad) values ("LA TENTACION");
    insert into ciudad (ciudad) values ("CERROS AZULES");
    insert into ciudad (ciudad) values ("QUEGUAYAR");
    insert into ciudad (ciudad) values ("BARRA DE MALDONADO");
    insert into ciudad (ciudad) values ("LA BARRA");
    insert into ciudad (ciudad) values ("VALENTINES");
    insert into ciudad (ciudad) values ("VALENTINES");
    insert into ciudad (ciudad) values ("SAUCE DE PORTEZUELO");
    insert into ciudad (ciudad) values ("LOS CORCHOS");
    insert into ciudad (ciudad) values ("ARENAS DE JOSE IGNACIO");
    insert into ciudad (ciudad) values ("PAYSANDU");
    insert into ciudad (ciudad) values ("BELLA VISTA");
    insert into ciudad (ciudad) values ("ESTACION PORVENIR");
    insert into ciudad (ciudad) values ("TERMAS DE ALMIRON");
    insert into ciudad (ciudad) values ("LOS ARRAYANES");
    insert into ciudad (ciudad) values ("PUEBLO RINCON DE VALENTIN");
    insert into ciudad (ciudad) values ("RINCON DE VALENTIN");
    insert into ciudad (ciudad) values ("CHACRAS DE PAYSANDU");
    insert into ciudad (ciudad) values ("BARRA DE VALIZAS");
    insert into ciudad (ciudad) values ("PUEBLO NUEVO");
    insert into ciudad (ciudad) values ("CUCHILLA DE GUAVIYU");
    insert into ciudad (ciudad) values ("RAIGON");
    insert into ciudad (ciudad) values ("MOIRONES");
    insert into ciudad (ciudad) values ("PUEBLO QUINTANA");
    insert into ciudad (ciudad) values ("SARANDI DE ARAPEY");
    insert into ciudad (ciudad) values ("LAS FLORES");
    insert into ciudad (ciudad) values ("RINCON DEL PINO");
    insert into ciudad (ciudad) values ("BARRIO CARPACHO");
    insert into ciudad (ciudad) values ("CAPACHO");
    insert into ciudad (ciudad) values ("RINCON DEL BONETE");
    insert into ciudad (ciudad) values ("CASTILLOS");
    insert into ciudad (ciudad) values ("PUEBLO CASTILLO");
    insert into ciudad (ciudad) values ("EL TALA");
    insert into ciudad (ciudad) values ("VILLA ANSINA");
    insert into ciudad (ciudad) values ("PERSEVERANO");
    insert into ciudad (ciudad) values ("PUEBLO DE ARRIBA");
    insert into ciudad (ciudad) values ("PUEBLO DEL BARRO");
    insert into ciudad (ciudad) values ("SAUCE DE BATOVI");
    insert into ciudad (ciudad) values ("RINCON DE PEREIRA");
    insert into ciudad (ciudad) values ("PUNTA DE CARRETERA");
    insert into ciudad (ciudad) values ("PUNTAS DEL PARAO");
    insert into ciudad (ciudad) values ("ARROCERA EL TIGRE");
    insert into ciudad (ciudad) values ("ARROCERA LA CATUMBERA");
    insert into ciudad (ciudad) values ("ARROCERA LA QUERENCIA");
    insert into ciudad (ciudad) values ("TOTORAL DEL SAUCE");
    insert into ciudad (ciudad) values ("LA LOMA");
    insert into ciudad (ciudad) values ("PALO SOLO");
    insert into ciudad (ciudad) values ("PAN DE AZUCAR");
    insert into ciudad (ciudad) values ("QUEBRACHO");
    insert into ciudad (ciudad) values ("PIERA");
    insert into ciudad (ciudad) values ("PIERA");
    insert into ciudad (ciudad) values ("ELIAS REGULES");
    insert into ciudad (ciudad) values ("ROSSELL Y RIUS");
    insert into ciudad (ciudad) values ("TARARIRAS");
    insert into ciudad (ciudad) values ("PASTOREO");
    insert into ciudad (ciudad) values ("LA PAZ");
    insert into ciudad (ciudad) values ("ESTACION CASTELLANOS");
    insert into ciudad (ciudad) values ("PUEBLO CASTELLANOS");
    insert into ciudad (ciudad) values ("BELLA VISTA");
    insert into ciudad (ciudad) values ("PLAYA GRANDE");
    insert into ciudad (ciudad) values ("MALDONADO");
    insert into ciudad (ciudad) values ("EJIDO DE TREINTA Y TRES");
    insert into ciudad (ciudad) values ("CARMELO");
    insert into ciudad (ciudad) values ("EL BELLACO");
    insert into ciudad (ciudad) values ("LA PEDRERA");
    insert into ciudad (ciudad) values ("CERRO DE PASTOREO");
    insert into ciudad (ciudad) values ("TALA");
    insert into ciudad (ciudad) values ("LA TUNA");
    insert into ciudad (ciudad) values ("SAN BAUTISTA");
    insert into ciudad (ciudad) values ("S BAUTISTA");
    insert into ciudad (ciudad) values ("LA HILERA");
    insert into ciudad (ciudad) values ("CERRO CHATO");
    insert into ciudad (ciudad) values ("CHILENO GRANDE (AGUERO)");
    insert into ciudad (ciudad) values ("MOLLES DE AIGUA");
    insert into ciudad (ciudad) values ("SAUCE DEL YI");
    insert into ciudad (ciudad) values ("ARROYO MALO");
    insert into ciudad (ciudad) values ("RINCON DE NAZARETH");
    insert into ciudad (ciudad) values ("TROPEZON");
    insert into ciudad (ciudad) values ("LA SIERRA");
    insert into ciudad (ciudad) values ("REAL DE VERA");
    insert into ciudad (ciudad) values ("CONCHILLAS");
    insert into ciudad (ciudad) values ("JOSE ENRIQUE RODO");
    insert into ciudad (ciudad) values ("CHISPAS");
    insert into ciudad (ciudad) values ("SACACHISPAS");
    insert into ciudad (ciudad) values ("VILLA DARWIN");
    insert into ciudad (ciudad) values ("CHACRAS DE DOLORES");
    insert into ciudad (ciudad) values ("RINCON DE RUIZ");
    insert into ciudad (ciudad) values ("ARBOLITO (TOTORAL)");
    insert into ciudad (ciudad) values ("PASO  VALEGA");
    insert into ciudad (ciudad) values ("PASO DE LA CRUZ");
    insert into ciudad (ciudad) values ("CARPINTERIA");
    insert into ciudad (ciudad) values ("MANUEL DIAZ");
    insert into ciudad (ciudad) values ("PASO SERPA");
    insert into ciudad (ciudad) values ("ZANJA HONDA DE TRANQUERAS");
    insert into ciudad (ciudad) values ("PRESIDENTE DOCTOR GETULIO VARGAS");
    insert into ciudad (ciudad) values ("ASPEREZAS");
    insert into ciudad (ciudad) values ("ARROYO MALO");
    insert into ciudad (ciudad) values ("PUNTAS DE MOLLES");
    insert into ciudad (ciudad) values ("CASA DE LAS CRONICAS");
    insert into ciudad (ciudad) values ("TRES ISLAS");
    insert into ciudad (ciudad) values ("CUCHILLA DEL CARMEN");
    insert into ciudad (ciudad) values ("ARROZAL TREINTA Y TRES");
    insert into ciudad (ciudad) values ("CERRO PELADO");
    insert into ciudad (ciudad) values ("PALO A PIQUE");
    insert into ciudad (ciudad) values ("COSTAS DE CEBOLLATI");
    insert into ciudad (ciudad) values ("LA FALDA");
    insert into ciudad (ciudad) values ("SARANDI DEL MATAOJO");
    insert into ciudad (ciudad) values ("VEJIGAS DE SAN RAMON");
    insert into ciudad (ciudad) values ("COSTA DE PANDO SAN JACINTO");
    insert into ciudad (ciudad) values ("COSTA DE PANDO OLMOS");
    insert into ciudad (ciudad) values ("PASO PALOMEQUE");
    insert into ciudad (ciudad) values ("VILLA ENCANTADA");
    insert into ciudad (ciudad) values ("PUERTO DE LOS BOTES");
    insert into ciudad (ciudad) values ("PUNTAS DE ARROYO NEGRO");
    insert into ciudad (ciudad) values ("CERAMICAS DEL SUR");
    insert into ciudad (ciudad) values ("HIPODROMO");
    insert into ciudad (ciudad) values ("BARRIO LA VINCHUCA");
    insert into ciudad (ciudad) values ("COLINAS DE CARRASCO");
    insert into ciudad (ciudad) values ("LOMAS DE CARRASCO");
    insert into ciudad (ciudad) values ("CASERIO LAS CAAS");
    insert into ciudad (ciudad) values ("VILLA EL TATO");
    insert into ciudad (ciudad) values ("PASO ESPINOSA");
    insert into ciudad (ciudad) values ("BARRIO LA LUCHA");
    insert into ciudad (ciudad) values ("VILLA SAN FELIPE");
    insert into ciudad (ciudad) values ("CERRO SIGNORELLI");
    insert into ciudad (ciudad) values ("CERRO SAN EUGENIO");
    insert into ciudad (ciudad) values ("COLON");
    insert into ciudad (ciudad) values ("COLONIA PALMA");
    insert into ciudad (ciudad) values ("LAS PALMAS");
    insert into ciudad (ciudad) values ("LA CAPUERA");
    insert into ciudad (ciudad) values ("BELLA UNION");
    insert into ciudad (ciudad) values ("BALTASAR BRUM");
    insert into ciudad (ciudad) values ("CERRO EJIDO");
    insert into ciudad (ciudad) values ("BERNABE RIVERA");
    insert into ciudad (ciudad) values ("B RIVERA");
    insert into ciudad (ciudad) values ("BARRIO LAS PIEDRAS");
    insert into ciudad (ciudad) values ("LAS PIEDRAS");
    insert into ciudad (ciudad) values ("FRANQUIA");
    insert into ciudad (ciudad) values ("SEQUEIRA");
    insert into ciudad (ciudad) values ("CORONADO");
    insert into ciudad (ciudad) values ("CUAREIM");
    insert into ciudad (ciudad) values ("CUARO");
    insert into ciudad (ciudad) values ("ESTACION CUARO");
    insert into ciudad (ciudad) values ("PORT. DE HIERRO Y CAMPODONICO");
    insert into ciudad (ciudad) values ("COLONIA LAVALLEJA");
    insert into ciudad (ciudad) values ("MIGLIARO");
    insert into ciudad (ciudad) values ("COLONIA MONES QUINTELA");
    insert into ciudad (ciudad) values ("MONES QUINTELA");
    insert into ciudad (ciudad) values ("25 DE AGOSTO");
    insert into ciudad (ciudad) values ("25 DE MAYO");
    insert into ciudad (ciudad) values ("CAINSA");
    insert into ciudad (ciudad) values ("CALPICA ITACUMBU\t");
    insert into ciudad (ciudad) values ("PARQUE POSTEL CNEL. ADRIAN MEDINA");
    insert into ciudad (ciudad) values ("PINAMAR");
    insert into ciudad (ciudad) values ("CANELONES");
    insert into ciudad (ciudad) values ("VIADUCTO CANELONES");
    insert into ciudad (ciudad) values ("CRUZ DE LOS CAMINOS");
    insert into ciudad (ciudad) values ("LA PAZ");
    insert into ciudad (ciudad) values ("PUEBLO RINCON DE RAMIREZ");
    insert into ciudad (ciudad) values ("RINCON");
    insert into ciudad (ciudad) values ("RIACHUELO");
    insert into ciudad (ciudad) values ("LA ASUNCION");
    insert into ciudad (ciudad) values ("SANTA LUCIA");
    insert into ciudad (ciudad) values ("PIEDRAS DE AFILAR");
    insert into ciudad (ciudad) values ("QUEBRACHO");
    insert into ciudad (ciudad) values ("COLONIA NICOLICH");
    insert into ciudad (ciudad) values ("LA PEDRERA");
    insert into ciudad (ciudad) values ("SAN RAMON");
    insert into ciudad (ciudad) values ("JOAQUIN SUAREZ");
    insert into ciudad (ciudad) values ("SUAREZ");
    insert into ciudad (ciudad) values ("MENDOZA GRANDE");
    insert into ciudad (ciudad) values ("JUAN SOLER");
    insert into ciudad (ciudad) values ("BALNEARIO LAGO MERIN");
    insert into ciudad (ciudad) values ("LAGO MERIN");
    insert into ciudad (ciudad) values ("LAS TOSCAS");
    insert into ciudad (ciudad) values ("PASO CARRASCO");
    insert into ciudad (ciudad) values ("SANTA ROSA");
    insert into ciudad (ciudad) values ("BARRIO COPOLA");
    insert into ciudad (ciudad) values ("SAUCE");
    insert into ciudad (ciudad) values ("PENINO");
    insert into ciudad (ciudad) values ("PASO DEL LAGUNON");
    insert into ciudad (ciudad) values ("PARQUE DEL PLATA");
    insert into ciudad (ciudad) values ("SAN LUIS");
    insert into ciudad (ciudad) values ("VILLA FELICIDAD");
    insert into ciudad (ciudad) values ("VILLA PAZ S.A.");
    insert into ciudad (ciudad) values ("CAMINO AL PASO DEL ANDALUZ");
    insert into ciudad (ciudad) values ("FRACC. CNO. ANDALUZ Y R.84");
    insert into ciudad (ciudad) values ("LOS CERRILLOS");
    insert into ciudad (ciudad) values ("SAN JACINTO");
    insert into ciudad (ciudad) values ("VILLA SAN JOSE");
    insert into ciudad (ciudad) values ("DOCTOR FRANCISCO SOCA");
    insert into ciudad (ciudad) values ("FRANCISCO SOCA");
    insert into ciudad (ciudad) values ("ESTACION TAPIA");
    insert into ciudad (ciudad) values ("MONTES");
    insert into ciudad (ciudad) values ("PINARES DE SOLYMAR");
    insert into ciudad (ciudad) values ("BOSQUE DE SOLYMAR");
    insert into ciudad (ciudad) values ("EL BOSQUE DE SOLYMAR");
    insert into ciudad (ciudad) values ("SAN JOSE DE CARRASCO");
    insert into ciudad (ciudad) values ("ESPERANZA");
    insert into ciudad (ciudad) values ("CITY PARK");
    insert into ciudad (ciudad) values ("PARQUE CARRASCO");
    insert into ciudad (ciudad) values ("JUANICO");
    insert into ciudad (ciudad) values ("GERONA");
    insert into ciudad (ciudad) values ("LA FLORESTA");
    insert into ciudad (ciudad) values ("PASO DE PACHE");
    insert into ciudad (ciudad) values ("MONTES DE SOLYMAR");
    insert into ciudad (ciudad) values ("PINTADITO");
    insert into ciudad (ciudad) values ("MARISCALA");
    insert into ciudad (ciudad) values ("POBLADO URUGUAY");
    insert into ciudad (ciudad) values ("SOLYMAR");
    insert into ciudad (ciudad) values ("DIEGO LAMAS");
    insert into ciudad (ciudad) values ("ROCHA");
    insert into ciudad (ciudad) values ("PLAYA HERMOSA");
    insert into ciudad (ciudad) values ("GUAZUVIRA NUEVO");
    insert into ciudad (ciudad) values ("BARKER");
    insert into ciudad (ciudad) values ("MELO");
    insert into ciudad (ciudad) values ("NUEVA CARRARA");
    insert into ciudad (ciudad) values ("NEPTUNIA");
    insert into ciudad (ciudad) values ("LA MONTAESA");
    insert into ciudad (ciudad) values ("GUAZUVIRA");
    insert into ciudad (ciudad) values ("LA BOLSA");
    insert into ciudad (ciudad) values ("BOLIVAR");
    insert into ciudad (ciudad) values ("PLANO 291");
    insert into ciudad (ciudad) values ("PANDO");
    insert into ciudad (ciudad) values ("CAPURRO");
    insert into ciudad (ciudad) values ("ESTANQUE DE PANDO");
    insert into ciudad (ciudad) values ("QUINTAS DEL BOSQUE");
    insert into ciudad (ciudad) values ("BARRIO REMANSO");
    insert into ciudad (ciudad) values ("CERRO CHATO");
    insert into ciudad (ciudad) values ("CERRO CHATO");
    insert into ciudad (ciudad) values ("CERRO CHATO");
    insert into ciudad (ciudad) values ("CHAMIZO");
    insert into ciudad (ciudad) values ("INDEPENDENCIA");
    insert into ciudad (ciudad) values ("CITY GOLF");
    insert into ciudad (ciudad) values ("PASO DEL CERRO");
    insert into ciudad (ciudad) values ("SAFICI");
    insert into ciudad (ciudad) values ("SAMUEL");
    insert into ciudad (ciudad) values ("QUINTA LOS HORNEROS");
    insert into ciudad (ciudad) values ("LAS HIGUERITAS");
    insert into ciudad (ciudad) values ("ESTACION PIEDRAS DE AFILAR");
    insert into ciudad (ciudad) values ("PUEBLO CENTENARIO");
    insert into ciudad (ciudad) values ("COSTA AZUL");
    insert into ciudad (ciudad) values ("COSTA Y GUILLAMON");
    insert into ciudad (ciudad) values ("MANGRULLO");
    insert into ciudad (ciudad) values ("MARINDIA");
    insert into ciudad (ciudad) values ("GARZON");
    insert into ciudad (ciudad) values ("ARACHANIA");
    insert into ciudad (ciudad) values ("HOSPITAL");
    insert into ciudad (ciudad) values ("JUAN CARLOS CASEROS");
    insert into ciudad (ciudad) values ("CHICO TORINO");
    insert into ciudad (ciudad) values ("PASO DE LOS NOVILLOS");
    insert into ciudad (ciudad) values ("RIVERA CHICO");
    insert into ciudad (ciudad) values ("VILLA RIVES");
    insert into ciudad (ciudad) values ("ARRIVILLAGA");
    insert into ciudad (ciudad) values ("PIEDRA SOLA");
    insert into ciudad (ciudad) values ("PIEDRA SOLA");
    insert into ciudad (ciudad) values ("CARLOS REYLES");
    insert into ciudad (ciudad) values ("POLANCO DEL YI");
    insert into ciudad (ciudad) values ("PUNTAS DE VALDEZ");
    insert into ciudad (ciudad) values ("ISIDORO NOBLIA");
    insert into ciudad (ciudad) values ("BAYGORRIA");
    insert into ciudad (ciudad) values ("SAN FERNANDO CHICO");
    insert into ciudad (ciudad) values ("AGUAS BUENAS");
    insert into ciudad (ciudad) values ("ARROYO SAUZAL");
    insert into ciudad (ciudad) values ("JAUREGUIBERRY");
    insert into ciudad (ciudad) values ("CERRO COLORADO");
    insert into ciudad (ciudad) values ("CASERIO LA FUNDACION");
    insert into ciudad (ciudad) values ("PARADA ESPERANZA");
    insert into ciudad (ciudad) values ("PUEBLO ESPERANZA");
    insert into ciudad (ciudad) values ("SARANDI DE NAVARRO");
    insert into ciudad (ciudad) values ("VILLA MARIA");
    insert into ciudad (ciudad) values ("PALOMAS");
    insert into ciudad (ciudad) values ("LLUVERAS");
    insert into ciudad (ciudad) values ("TRANQUERAS");
    insert into ciudad (ciudad) values ("CARDOSO");
    insert into ciudad (ciudad) values ("BLANES VIALE");
    insert into ciudad (ciudad) values ("BEISSO");
    insert into ciudad (ciudad) values ("FRIGORIFICO MODELO");
    insert into ciudad (ciudad) values ("ESCUELA DE AGRONOMIA");
    insert into ciudad (ciudad) values ("LOS TALAS");
    insert into ciudad (ciudad) values ("CUCHILLA DE PERALTA");
    insert into ciudad (ciudad) values ("WENCESLAO SILVERA");
    insert into ciudad (ciudad) values ("LOS MELLIZOS");
    insert into ciudad (ciudad) values ("SAN GREGORIO DE POLANCO");
    insert into ciudad (ciudad) values ("ARBOLITO");
    insert into ciudad (ciudad) values ("CERRO DE LAS CUENTAS");
    insert into ciudad (ciudad) values ("PUEBLO ALONZO");
    insert into ciudad (ciudad) values ("SAN JAVIER");
    insert into ciudad (ciudad) values ("CHAMBERLAIN");
    insert into ciudad (ciudad) values ("YOUNG");
    insert into ciudad (ciudad) values ("LA PALOMA");
    insert into ciudad (ciudad) values ("SANTA CLARA DE OLIMAR");
    insert into ciudad (ciudad) values ("OSIMANI Y LLERENA");
    insert into ciudad (ciudad) values ("SAN JOSE DE MAYO");
    insert into ciudad (ciudad) values ("VERGARA");
    insert into ciudad (ciudad) values ("ARAUJO");
    insert into ciudad (ciudad) values ("TUPAMBAE");
    insert into ciudad (ciudad) values ("TUPAMBAE");
    insert into ciudad (ciudad) values ("MARIA ISABEL");
    insert into ciudad (ciudad) values ("PALMAR");
    insert into ciudad (ciudad) values ("MENAFRA");
    insert into ciudad (ciudad) values ("TRES QUINTAS");
    insert into ciudad (ciudad) values ("PUNTAS DE VALENTIN");
    insert into ciudad (ciudad) values ("MERCEDES");
    insert into ciudad (ciudad) values ("MENDIZABAL");
    insert into ciudad (ciudad) values ("GRAL. ENRIQUE MARTINEZ");
    insert into ciudad (ciudad) values ("LA CHARQUEADA");
    insert into ciudad (ciudad) values ("PUEBLO GENERAL ENRIQUE MARTINEZ");
    insert into ciudad (ciudad) values ("EL PINAR");
    insert into ciudad (ciudad) values ("SAN CARLOS");
    insert into ciudad (ciudad) values ("TREINTA Y TRES");
    insert into ciudad (ciudad) values ("VILLA DEL CARMEN");
    insert into ciudad (ciudad) values ("VILLA SARA");
    insert into ciudad (ciudad) values ("ARGENTINO");
    insert into ciudad (ciudad) values ("MANGRULLO");
    insert into ciudad (ciudad) values ("VILLA PASSANO");
    insert into ciudad (ciudad) values ("DE DIOS");
    insert into ciudad (ciudad) values ("GOI");
    insert into ciudad (ciudad) values ("ESTACION MONTECORAL");
    insert into ciudad (ciudad) values ("MONTECORAL");
    insert into ciudad (ciudad) values ("PASO DEL PARQUE DEL DAYMAN");
    insert into ciudad (ciudad) values ("CELESTE");
    insert into ciudad (ciudad) values ("PUEBLO CELESTE");
    insert into ciudad (ciudad) values ("CUCHILLA ALTA");
    insert into ciudad (ciudad) values ("DOLORES");
    insert into ciudad (ciudad) values ("LA CONCORDIA");
    insert into ciudad (ciudad) values ("ILLESCAS");
    insert into ciudad (ciudad) values ("ILLESCAS");
    insert into ciudad (ciudad) values ("EGAA");
    insert into ciudad (ciudad) values ("EGAA");
    insert into ciudad (ciudad) values ("RISSO");
    insert into ciudad (ciudad) values ("LASCANO");
    insert into ciudad (ciudad) values ("VILLA SORIANO");
    insert into ciudad (ciudad) values ("CAADA NIETO");
    insert into ciudad (ciudad) values ("ALEJANDRO GALLINAL");
    insert into ciudad (ciudad) values ("CERRO COLORADO");
    insert into ciudad (ciudad) values ("CARDONA");
    insert into ciudad (ciudad) values ("CUCHILLA DEL PERDIDO");
    insert into ciudad (ciudad) values ("SANTA ANA");
    insert into ciudad (ciudad) values ("SANTA LUCIA DEL ESTE");
    insert into ciudad (ciudad) values ("ISMAEL CORTINAS");
    insert into ciudad (ciudad) values ("ARROCERA BONOMO");
    insert into ciudad (ciudad) values ("COLONIA MIGUELETE");
    insert into ciudad (ciudad) values ("CUCHILLA DEL OMBU");
    insert into ciudad (ciudad) values ("MAL ABRIGO");
    insert into ciudad (ciudad) values ("OMBUES DE LAVALLE");
    insert into ciudad (ciudad) values ("VELAZQUEZ");
    insert into ciudad (ciudad) values ("CASUPA");
    insert into ciudad (ciudad) values ("VILLA DEL ROSARIO");
    insert into ciudad (ciudad) values ("COLINAS DE SOLYMAR");
    insert into ciudad (ciudad) values ("POBLADO ALONZO");
    insert into ciudad (ciudad) values ("SALTO");
    insert into ciudad (ciudad) values ("AEROPUERTO INTERNACIONAL DE CARRASCO");
    insert into ciudad (ciudad) values ("FRAY MARCOS");
    insert into ciudad (ciudad) values ("AIGUA");
    insert into ciudad (ciudad) values ("CUFRE");
    insert into ciudad (ciudad) values ("GONZALEZ");
    insert into ciudad (ciudad) values ("PARADA CABRERA");
    insert into ciudad (ciudad) values ("JARDINES DE PANDO");
    insert into ciudad (ciudad) values ("CARMEL");
    insert into ciudad (ciudad) values ("LA PEDRERA");
    insert into ciudad (ciudad) values ("SHANGRILA");
    insert into ciudad (ciudad) values ("GALLINAL");
    insert into ciudad (ciudad) values ("CAMPO MILITAR");
    insert into ciudad (ciudad) values ("EL BOSQUE");
    insert into ciudad (ciudad) values ("EL BOSQUE DE CARRASCO");
    insert into ciudad (ciudad) values ("ESTACION PEDRERA");
    insert into ciudad (ciudad) values ("FRACCIONAMIENTO PROGRESO");
    insert into ciudad (ciudad) values ("FRACC. PROGRESO");
    insert into ciudad (ciudad) values ("NANDO");
    insert into ciudad (ciudad) values ("PASO DE LA CADENA");
    insert into ciudad (ciudad) values ("EL EDEN");
    insert into ciudad (ciudad) values ("PASO DEL TORO");
    insert into ciudad (ciudad) values ("PIEDRA DEL TORO");
    insert into ciudad (ciudad) values ("VILLA SAN CONO");
    insert into ciudad (ciudad) values ("VILLA JUANA");
    insert into ciudad (ciudad) values ("EL GALEON");
    insert into ciudad (ciudad) values ("SEIS HERMANOS");
    insert into ciudad (ciudad) values ("VILLA AREJO");
    insert into ciudad (ciudad) values ("VILLA ARGENTINA");
    insert into ciudad (ciudad) values ("ARROCERA LAS PALMAS");
    insert into ciudad (ciudad) values ("ANDRESITO");
    insert into ciudad (ciudad) values ("ALTOS DE LA TAHONA");
    insert into ciudad (ciudad) values ("ARROCERA MINI");
    insert into ciudad (ciudad) values ("ACEGUA");
    insert into ciudad (ciudad) values ("ALMEIDA");
    insert into ciudad (ciudad) values ("JUNCAL");
    insert into ciudad (ciudad) values ("PASO ALMEIDA");
    insert into ciudad (ciudad) values ("PUEBLO ALMEIDA");
    insert into ciudad (ciudad) values ("PUEBLO JUNCAL");
    insert into ciudad (ciudad) values ("BAADO DE MEDINA");
    insert into ciudad (ciudad) values ("JUAN JOSE CASTRO");
    insert into ciudad (ciudad) values ("ARROCERA PROCIPA");
    insert into ciudad (ciudad) values ("CENTURION");
    insert into ciudad (ciudad) values ("AREVALO");
    insert into ciudad (ciudad) values ("ANGAPIRE");
    insert into ciudad (ciudad) values ("COLONIA SUIZA");
    insert into ciudad (ciudad) values ("NUEVA HELVECIA");
    insert into ciudad (ciudad) values ("JUAN LACAZE");
    insert into ciudad (ciudad) values ("CERROS DE SAN JUAN");
    insert into ciudad (ciudad) values ("ROSARIO");
    insert into ciudad (ciudad) values ("PLACIDO ROSAS");
    insert into ciudad (ciudad) values ("SAN GABRIEL");
    insert into ciudad (ciudad) values ("PASO ANTOLIN");
    insert into ciudad (ciudad) values ("CASERIO EL CERRO");
    insert into ciudad (ciudad) values ("EL SEMILLERO");
    insert into ciudad (ciudad) values ("PASO BONILLA");
    insert into ciudad (ciudad) values ("CAMPANA");
    insert into ciudad (ciudad) values ("ARTILLEROS");
    insert into ciudad (ciudad) values ("BALNEARIO ARTILLEROS");
    insert into ciudad (ciudad) values ("P.ASTILLERO");
    insert into ciudad (ciudad) values ("BLANCA ARENA");
    insert into ciudad (ciudad) values ("BRISAS DEL PLATA");
    insert into ciudad (ciudad) values ("COLONIA COSMOPOLITA");
    insert into ciudad (ciudad) values ("PARAJE MINUANO");
    insert into ciudad (ciudad) values ("RADIAL HERNANDEZ");
    insert into ciudad (ciudad) values ("BALNEARIO BRITOPOLIS");
    insert into ciudad (ciudad) values ("PLAYA BRITOPOLIS");
    insert into ciudad (ciudad) values ("BALNEARIO SANTA ANA");
    insert into ciudad (ciudad) values ("SANTA ANA");
    insert into ciudad (ciudad) values ("LOS PINOS");
    insert into ciudad (ciudad) values ("PLAYA AZUL");
    insert into ciudad (ciudad) values ("PLAYA PARANT");
    insert into ciudad (ciudad) values ("PUERTO INGLES");
    insert into ciudad (ciudad) values ("BALNEARIO ZAGARZAU");
    insert into ciudad (ciudad) values ("BALNEARIO ZAGARZAZU");
    insert into ciudad (ciudad) values ("ZAGARZAZU");
    insert into ciudad (ciudad) values ("EL FARO");
    insert into ciudad (ciudad) values ("LAGUNA DE LOS PATOS");
    insert into ciudad (ciudad) values ("CERRO CARMELO");
    insert into ciudad (ciudad) values ("FELICIANO");
    insert into ciudad (ciudad) values ("OMBUES DE ORIBE");
    insert into ciudad (ciudad) values ("SAN JORGE");
    insert into ciudad (ciudad) values ("MERINOS");
    insert into ciudad (ciudad) values ("MERINOS");
    insert into ciudad (ciudad) values ("BARCELO");
    insert into ciudad (ciudad) values ("ESTACION PINTADO");
    insert into ciudad (ciudad) values ("PINTADO");
    insert into ciudad (ciudad) values ("TRINIDAD");
    insert into ciudad (ciudad) values ("SARANDI GRANDE");
    insert into ciudad (ciudad) values ("CAPILLA DEL SAUCE");
    insert into ciudad (ciudad) values ("REBOLEDO");
    insert into ciudad (ciudad) values ("BERRONDO");
    insert into ciudad (ciudad) values ("PIRARAJA");
    insert into ciudad (ciudad) values ("NICO PEREZ");
    insert into ciudad (ciudad) values ("ESTACION SOLIS");
    insert into ciudad (ciudad) values ("GAETAN (CUCHILLA DE CARBAJAL)");
    insert into ciudad (ciudad) values ("SOLIS DE MATAOJO");
    insert into ciudad (ciudad) values ("EL EUCALIPTUS");
    insert into ciudad (ciudad) values ("VILLA SERRANA");
    insert into ciudad (ciudad) values ("BARRIO LA CORONILLA - ANCAP");
    insert into ciudad (ciudad) values ("SAN FRANCISCO DE LAS SIERRAS");
    insert into ciudad (ciudad) values ("ACHAR");
    insert into ciudad (ciudad) values ("ZAPICAN");
    insert into ciudad (ciudad) values ("19 DE JUNIO");
    insert into ciudad (ciudad) values ("CAADA DEL PUEBLO");
    insert into ciudad (ciudad) values ("CLAVIJO");
    insert into ciudad (ciudad) values ("CERRO PELADO");
    insert into ciudad (ciudad) values ("LAS FLORES - ESTACION");
    insert into ciudad (ciudad) values ("SOLIS");
    insert into ciudad (ciudad) values ("PUEBLO SOLIS");
    insert into ciudad (ciudad) values ("LOS AROMOS");
    insert into ciudad (ciudad) values ("CHIHUAHUA");
    insert into ciudad (ciudad) values ("VILLA DELIA");
    insert into ciudad (ciudad) values ("CHAPICUY");
    insert into ciudad (ciudad) values ("MORATO (TRES ARBOLES)");
    insert into ciudad (ciudad) values ("PINARES - LAS DELICIAS");
    insert into ciudad (ciudad) values ("EL QUINTON");
    insert into ciudad (ciudad) values ("EL TESORO");
    insert into ciudad (ciudad) values ("GUAVIYU DE ARAPEY");
    insert into ciudad (ciudad) values ("EL QUIJOTE");
    insert into ciudad (ciudad) values ("RUSSO");
    insert into ciudad (ciudad) values ("PASO CEMENTERIO");
    insert into ciudad (ciudad) values ("LAGUNA BLANCA");
    insert into ciudad (ciudad) values ("19 DE ABRIL");
    insert into ciudad (ciudad) values ("PUNTA COLORADA");
    insert into ciudad (ciudad) values ("PUNTA NEGRA");
    insert into ciudad (ciudad) values ("RUTA 37 Y 9");
    insert into ciudad (ciudad) values ("SAN VICENTE");
    insert into ciudad (ciudad) values ("LA MACANA");
    insert into ciudad (ciudad) values ("JOSE BATLLE Y ORDONEZ");
    insert into ciudad (ciudad) values ("JOSE BATLLE Y ORDOEZ");
    insert into ciudad (ciudad) values ("JOSE BATLLE Y ORDONEZ");
    insert into ciudad (ciudad) values ("JOSE BATLLE Y ORDOEZ");
    insert into ciudad (ciudad) values ("VICHADERO");
    insert into ciudad (ciudad) values ("BALNEARIO BUENOS AIRES");
    insert into ciudad (ciudad) values ("LAS CUMBRES");
    insert into ciudad (ciudad) values ("PARQUE MIRAMAR");
    insert into ciudad (ciudad) values ("BLANCO");
    insert into ciudad (ciudad) values ("SANTA MONICA");
    insert into ciudad (ciudad) values ("EDEN ROCK");
    insert into ciudad (ciudad) values ("PARQUE MEDINA");
    insert into ciudad (ciudad) values ("LA SONRISA");
    insert into ciudad (ciudad) values ("TAMBORES");
    insert into ciudad (ciudad) values ("TAMBORES");
    insert into ciudad (ciudad) values ("GUICHON");
    insert into ciudad (ciudad) values ("PORVENIR");
    insert into ciudad (ciudad) values ("ORGOROSO");
    insert into ciudad (ciudad) values ("SOTO");
    insert into ciudad (ciudad) values ("CERRO CHATO");
    insert into ciudad (ciudad) values ("CONSTANCIA");
    insert into ciudad (ciudad) values ("PIEDRAS COLORA");
    insert into ciudad (ciudad) values ("PIEDRAS COLORADAS");
    insert into ciudad (ciudad) values ("ZEBALLOS");
    insert into ciudad (ciudad) values ("TERMAS DE GUAVIYU");
    insert into ciudad (ciudad) values ("LAGOS DEL NORTE");
    insert into ciudad (ciudad) values ("SAN FELIX");
    insert into ciudad (ciudad) values ("VILLA MARIA (TIATUCURA)");
    insert into ciudad (ciudad) values ("SANTA BERNARDINA");
    insert into ciudad (ciudad) values ("FRAY BENTOS");
    insert into ciudad (ciudad) values ("OLIVERA");
    insert into ciudad (ciudad) values ("CARRETA QUEMADA");
    insert into ciudad (ciudad) values ("BORGES");
    insert into ciudad (ciudad) values ("VILLA GENERAL BORGES");
    insert into ciudad (ciudad) values ("COLONIA EL OMBU");
    insert into ciudad (ciudad) values ("ARROYO BLANCO");
    insert into ciudad (ciudad) values ("PASO DE LAS PIEDRAS DE ARERUNGUA");
    insert into ciudad (ciudad) values ("SANTA TERESA");
    insert into ciudad (ciudad) values ("PASO ATAQUES");
    insert into ciudad (ciudad) values ("LAS FLORES");
    insert into ciudad (ciudad) values ("CERRO PELADO");
    insert into ciudad (ciudad) values ("CERRILLADA");
    insert into ciudad (ciudad) values ("COSTAS DE PEREIRA");
    insert into ciudad (ciudad) values ("RAPETTI");
    insert into ciudad (ciudad) values ("MANDUBI");
    insert into ciudad (ciudad) values ("LAGUNON");
    insert into ciudad (ciudad) values ("AMARILLO");
    insert into ciudad (ciudad) values ("COLONIA DELTA");
    insert into ciudad (ciudad) values ("RAFAEL PERAZZA");
    insert into ciudad (ciudad) values ("BOCA DEL ROSARIO OESTE");
    insert into ciudad (ciudad) values ("PALMARES DE LA CORONILLA");
    insert into ciudad (ciudad) values ("LA RIBIERA");
    insert into ciudad (ciudad) values ("PUENTE VALIZAS");
    insert into ciudad (ciudad) values ("PARQUE BALNEARIO LA PALOMA");
    insert into ciudad (ciudad) values ("PUERTO LA PALOMA");
    insert into ciudad (ciudad) values ("LA AGUADA Y COSTA AZUL");
    insert into ciudad (ciudad) values ("AGUAS DULCES");
    insert into ciudad (ciudad) values ("BARRA DEL CHUY");
    insert into ciudad (ciudad) values ("BARRIO TORRES");
    insert into ciudad (ciudad) values ("RADIAL RUTA 3");
    insert into ciudad (ciudad) values ("CABO POLONIO");
    insert into ciudad (ciudad) values ("BALNEARIO LA ESMERALDA");
    insert into ciudad (ciudad) values ("LA ESMERALDA");
    insert into ciudad (ciudad) values ("PARALLE");
    insert into ciudad (ciudad) values ("PUIMAYEN");
    insert into ciudad (ciudad) values ("ARACHANIA");
    insert into ciudad (ciudad) values ("PUNTA DEL DIABLO");
    insert into ciudad (ciudad) values ("OCEANIA DEL POLONIO");
    insert into ciudad (ciudad) values ("SAN ANTONIO");
    insert into ciudad (ciudad) values ("SAN ANTONIO");
    insert into ciudad (ciudad) values ("COLONIA 18 DE JULIO");
    insert into ciudad (ciudad) values ("SAUCEDO");
    insert into ciudad (ciudad) values ("TERMAS DEL ARAPEY");
    insert into ciudad (ciudad) values ("MINAS DE CORRALES");
    insert into ciudad (ciudad) values ("LAURELES");
    insert into ciudad (ciudad) values ("LIBERTAD");
    insert into ciudad (ciudad) values ("CONSTITUCION");
    insert into ciudad (ciudad) values ("PARQUE JOSE LUIS");
    insert into ciudad (ciudad) values ("PUEBLO FERNANDEZ");
    insert into ciudad (ciudad) values ("COLONIA ITAPEBI");
    insert into ciudad (ciudad) values ("BALNEARIO ALBISU");
    insert into ciudad (ciudad) values ("BIASSINI");
    insert into ciudad (ciudad) values ("PUEBLO BIASSINI");
    insert into ciudad (ciudad) values ("CAMPO DE TODOS");
    insert into ciudad (ciudad) values ("SAN FERNANDO");
    insert into ciudad (ciudad) values ("ARENITAS BLANCAS");
    insert into ciudad (ciudad) values ("CERROS DE VERA");
    insert into ciudad (ciudad) values ("GARIBALDI");
    insert into ciudad (ciudad) values ("ITUZAINGO");
    insert into ciudad (ciudad) values ("BOCA DE CUFRE");
    insert into ciudad (ciudad) values ("BOCA DEL CUFRE");
    insert into ciudad (ciudad) values ("VILLA MARIA");
    insert into ciudad (ciudad) values ("MONTE GRANDE");
    insert into ciudad (ciudad) values ("ECILDA PAULLIER");
    insert into ciudad (ciudad) values ("ADOLFO SCAVINO");
    insert into ciudad (ciudad) values ("SCAVINO");
    insert into ciudad (ciudad) values ("PALMITAS");
    insert into ciudad (ciudad) values ("SANTA CATALINA");
    insert into ciudad (ciudad) values ("TAJAMARES DE LA PEDRERA");
    insert into ciudad (ciudad) values ("ARROCERA LOS TEROS");
    insert into ciudad (ciudad) values ("CURTINA");
    insert into ciudad (ciudad) values ("CLARA");
    insert into ciudad (ciudad) values ("LAS TOSCAS DE CARAGUATA");
    insert into ciudad (ciudad) values ("LAURELES");
    insert into ciudad (ciudad) values ("CRUZ DE LOS CAMINOS");
    insert into ciudad (ciudad) values ("ARROCERA LOS CEIBOS");
    insert into ciudad (ciudad) values ("MARIA ALBINA");
    insert into ciudad (ciudad) values ("VILLA MARIA ALBINA");
    insert into ciudad (ciudad) values ("ARROCERA RINCON");
    insert into ciudad (ciudad) values ("ARROCERA SANTA FE");
    insert into ciudad (ciudad) values ("ARROCERA ZAPATA");
    insert into ciudad (ciudad) values ("SOTO GORO");
    insert into ciudad (ciudad) values ("BELLACO");
    insert into ciudad (ciudad) values ("SAN GREGORIO");
    insert into ciudad (ciudad) values ("LAS VEGAS");
    insert into ciudad (ciudad) values ("COLONIA CONCORDIA");
    insert into ciudad (ciudad) values ("CONCORDIA");
    insert into ciudad (ciudad) values ("PARQUE DE SOLYMAR");
    insert into ciudad (ciudad) values ("MONTEVIDEO CHICO");
    insert into ciudad (ciudad) values ("PUNTAS DE CINCO SAUCES");
    insert into ciudad (ciudad) values ("COLONIA DR. BERNARDO ETCHEPARE");
    insert into ciudad (ciudad) values ("BARRA DE PORTEZUELO");
    insert into ciudad (ciudad) values ("SAN FRANCISCO");
    insert into ciudad (ciudad) values ("BALNEARIO IPORA");
    insert into ciudad (ciudad) values ("PARQUE POSTEL");
    insert into ciudad (ciudad) values ("BUENOS AIRES");
    insert into ciudad (ciudad) values ("SAN SEBASTIAN DE LA PEDRERA");
    insert into ciudad (ciudad) values ("LAS CHIRCAS");
    insert into ciudad (ciudad) values ("LAS PAJAS");
    insert into ciudad (ciudad) values ("MINUANO");
    insert into ciudad (ciudad) values ("LOS VAZQUEZ");
    insert into ciudad (ciudad) values ("LOS ROSAS");
    insert into ciudad (ciudad) values ("TURUPI");
    insert into ciudad (ciudad) values ("PICADA DE CUELLO");
    insert into ciudad (ciudad) values ("CINCO SAUCES");
    insert into ciudad (ciudad) values ("CERRO DE PEREIRA");
    insert into ciudad (ciudad) values ("LOS FEOS");
    insert into ciudad (ciudad) values ("CUCHILLA DE LA PALMA");
    insert into ciudad (ciudad) values ("LA BOLSA 01");
    insert into ciudad (ciudad) values ("HERIBERTO");
    insert into ciudad (ciudad) values ("COSTAS DE TRES CRUCES");
    insert into ciudad (ciudad) values ("RINCON DE GILOCA");
    insert into ciudad (ciudad) values ("ZAPUCAY");
    insert into ciudad (ciudad) values ("ZAMBULLON");
    insert into ciudad (ciudad) values ("LOS SEMPER");
    insert into ciudad (ciudad) values ("RINCON DE LA LAGUNA");
    insert into ciudad (ciudad) values ("SAN JOAQUIN");
    insert into ciudad (ciudad) values ("RINCON DE ZAMORA");
    insert into ciudad (ciudad) values ("PASO DE LAS FLORES");
    insert into ciudad (ciudad) values ("CUCHILLA DE LAURELES");
    insert into ciudad (ciudad) values ("PASO DEL MEDIO");
    insert into ciudad (ciudad) values ("PASO DE CEFERINO");
    insert into ciudad (ciudad) values ("LAMBARE");
    insert into ciudad (ciudad) values ("PASO DE LAS CARRETAS");
    insert into ciudad (ciudad) values ("ATAQUE");
    insert into ciudad (ciudad) values ("BAADO DE ROCHA");
    insert into ciudad (ciudad) values ("CAAS");
    insert into ciudad (ciudad) values ("ZAPARA");
    insert into ciudad (ciudad) values ("SAUCE SOLO");
    insert into ciudad (ciudad) values ("LA PALMA");
    insert into ciudad (ciudad) values ("LA ALDEA");
    insert into ciudad (ciudad) values ("RINCON DE LA ALDEA");
    insert into ciudad (ciudad) values ("TIERRAS COLORADAS");
    insert into ciudad (ciudad) values ("RINCON DE LA BOLSA");
    insert into ciudad (ciudad) values ("LOS COITINHOS");
    insert into ciudad (ciudad) values ("SAUCE DE TRANQUERAS");
    insert into ciudad (ciudad) values ("BARRIO LIBERTAD");
    insert into ciudad (ciudad) values ("CERRO BATOVI");
    insert into ciudad (ciudad) values ("MARTINOTE");
    insert into ciudad (ciudad) values ("COYO MARTINEZ");
    insert into ciudad (ciudad) values ("CERROS DE CLARA");
    insert into ciudad (ciudad) values ("LOS CUADRADOS");
    insert into ciudad (ciudad) values ("COLMAN");
    insert into ciudad (ciudad) values ("RINCON DE LOS MACHADO");
    insert into ciudad (ciudad) values ("ONCE CERROS");
    insert into ciudad (ciudad) values ("CERRO DEL ARBOLITO");
    insert into ciudad (ciudad) values ("LOS FURTADOS");
    insert into ciudad (ciudad) values ("ARROYO DEL MEDIO");
    insert into ciudad (ciudad) values ("CHARATA");
    insert into ciudad (ciudad) values ("PASO HONDO");
    insert into ciudad (ciudad) values ("BLANQUILLOS");
    insert into ciudad (ciudad) values ("SAN BENITO");
    insert into ciudad (ciudad) values ("PUNTAS DE LAURELES");
    insert into ciudad (ciudad) values ("LOS LAURELES");
    insert into ciudad (ciudad) values ("CARPINTERIA");
    insert into ciudad (ciudad) values ("LOS CERROS");
    insert into ciudad (ciudad) values ("RINCON DE FREITAS");
    insert into ciudad (ciudad) values ("PASO VICTOR");
    insert into ciudad (ciudad) values ("CUCHILLA DE LA CASA DE PIEDRA");
    insert into ciudad (ciudad) values ("TACUAREMBO CHICO");
    insert into ciudad (ciudad) values ("VALLE EDEN");
    insert into ciudad (ciudad) values ("LOS ROSANOS");
    insert into ciudad (ciudad) values ("EL EMPALME");
    insert into ciudad (ciudad) values ("LOS RODRIGUEZ");
    insert into ciudad (ciudad) values ("PASO DE PEREZ");
    insert into ciudad (ciudad) values ("PAMPA");
    insert into ciudad (ciudad) values ("CARDOZO CHICO");
    insert into ciudad (ciudad) values ("CHURCHILL");
    insert into ciudad (ciudad) values ("CERREZUELO");
    insert into ciudad (ciudad) values ("PASO DEL MEDIO LAS PALMAS");
    insert into ciudad (ciudad) values ("CUCHILLA DE RAMIREZ");
    insert into ciudad (ciudad) values ("LA MAZAMORRA");
    insert into ciudad (ciudad) values ("LA ALEGRIA");
    insert into ciudad (ciudad) values ("PASO RAMIREZ");
    insert into ciudad (ciudad) values ("VERDUN");
    insert into ciudad (ciudad) values ("CERRO CONVENTO");
    insert into ciudad (ciudad) values ("CEIBAL");
    insert into ciudad (ciudad) values ("CAPILLA DE FARRUCO");
    insert into ciudad (ciudad) values ("CAPILLA FARRUCO");
    insert into ciudad (ciudad) values ("LAS ACACIAS");
    insert into ciudad (ciudad) values ("CHILENO");
    insert into ciudad (ciudad) values ("BLANQUILLO AL OESTE");
    insert into ciudad (ciudad) values ("ESTACION CHILENO");
    insert into ciudad (ciudad) values ("CHILENO CHICO");
    insert into ciudad (ciudad) values ("PUNTAS DE HERRERA");
    insert into ciudad (ciudad) values ("PUNTAS DE MALBAJAR");
    insert into ciudad (ciudad) values ("PASO DE AGUIRRE");
    insert into ciudad (ciudad) values ("MALBAJAR OESTE");
    insert into ciudad (ciudad) values ("MALBAJAR ESTE");
    insert into ciudad (ciudad) values ("SARANDI DEL RIO NEGRO");
    insert into ciudad (ciudad) values ("SARANDI DE RIO NEGRO");
    insert into ciudad (ciudad) values ("BARRANCAS COLORADAS");
    insert into ciudad (ciudad) values ("LOS AGREGADOS");
    insert into ciudad (ciudad) values ("HIGUERAS DE CARPINTERIA");
    insert into ciudad (ciudad) values ("PASO REAL DE CARPINTERIA");
    insert into ciudad (ciudad) values ("CUCHILLA DEL RINCON");
    insert into ciudad (ciudad) values ("ARROYO DE LOS PERROS");
    insert into ciudad (ciudad) values ("FONSECA");
    insert into ciudad (ciudad) values ("PUNTAS DE CARPINTERIA");
    insert into ciudad (ciudad) values ("MUNICIPIO DE DURAZNO");
    insert into ciudad (ciudad) values ("SAUCE DE HERRERA");
    insert into ciudad (ciudad) values ("ROLON");
    insert into ciudad (ciudad) values ("SALINAS");
    insert into ciudad (ciudad) values ("SALINAS CHICO");
    insert into ciudad (ciudad) values ("ABELLA");
    insert into ciudad (ciudad) values ("MARISCALA DEL CARMEN");
    insert into ciudad (ciudad) values ("MARISCALA");
    insert into ciudad (ciudad) values ("PASO DE CASTRO");
    insert into ciudad (ciudad) values ("SAUCE DEL YI");
    insert into ciudad (ciudad) values ("TALA DE MARISCALA");
    insert into ciudad (ciudad) values ("SARANDI DE LA CHINA");
    insert into ciudad (ciudad) values ("LARROSA");
    insert into ciudad (ciudad) values ("PARADA SUR");
    insert into ciudad (ciudad) values ("ESTACION PARISH");
    insert into ciudad (ciudad) values ("PARISH");
    insert into ciudad (ciudad) values ("MOLLES CHICO");
    insert into ciudad (ciudad) values ("MARIA CEJAS");
    insert into ciudad (ciudad) values ("PUGLIA");
    insert into ciudad (ciudad) values ("VILLASBOAS");
    insert into ciudad (ciudad) values ("COSTA DE CUADRA");
    insert into ciudad (ciudad) values ("TEJERA");
    insert into ciudad (ciudad) values ("SANDU CHICO");
    insert into ciudad (ciudad) values ("PASO TEJERA");
    insert into ciudad (ciudad) values ("LAS TUNAS");
    insert into ciudad (ciudad) values ("BATOVI");
    insert into ciudad (ciudad) values ("MAESTRE CAMPO");
    insert into ciudad (ciudad) values ("MOLLES DE QUINTEROS");
    insert into ciudad (ciudad) values ("LOS TAPES");
    insert into ciudad (ciudad) values ("CABALLERO");
    insert into ciudad (ciudad) values ("CHACRAS DE DURAZNO");
    insert into ciudad (ciudad) values ("RINCON DE LOS TAPES");
    insert into ciudad (ciudad) values ("COSTAS DE CORRALES");
    insert into ciudad (ciudad) values ("ALONSO");
    insert into ciudad (ciudad) values ("CARNALES");
    insert into ciudad (ciudad) values ("GUTIERREZ");
    insert into ciudad (ciudad) values ("SARANDI DE GUTIERREZ");
    insert into ciudad (ciudad) values ("RINCON DE CEBOLLATI");
    insert into ciudad (ciudad) values ("AZUCAR");
    insert into ciudad (ciudad) values ("LAS ACHIRAS");
    insert into ciudad (ciudad) values ("RINCON DE MARISCALA");
    insert into ciudad (ciudad) values ("MOLLES DEL SAUCE");
    insert into ciudad (ciudad) values ("SAUCE DE OLIMAR CHICO");
    insert into ciudad (ciudad) values ("RETAMOSA");
    insert into ciudad (ciudad) values ("MOLLES DE CAADA GRANDE");
    insert into ciudad (ciudad) values ("RINCON DE SILVA");
    insert into ciudad (ciudad) values ("LOS TAPES");
    insert into ciudad (ciudad) values ("PASO DE MESA");
    insert into ciudad (ciudad) values ("BARRIGA NEGRA");
    insert into ciudad (ciudad) values ("TAPES GRANDE");
    insert into ciudad (ciudad) values ("TAPES CHICO");
    insert into ciudad (ciudad) values ("PUNTAS DE BARRIGA NEGRA");
    insert into ciudad (ciudad) values ("MARMARAJA");
    insert into ciudad (ciudad) values ("PASO DE LOS TRONCOS");
    insert into ciudad (ciudad) values ("CERRO PELADO");
    insert into ciudad (ciudad) values ("PORORO");
    insert into ciudad (ciudad) values ("PUENTE DE MARMARAJA");
    insert into ciudad (ciudad) values ("SAUCE DE AIGUA");
    insert into ciudad (ciudad) values ("MARCO DE LOS REYES");
    insert into ciudad (ciudad) values ("GODOY");
    insert into ciudad (ciudad) values ("LADRILLOS");
    insert into ciudad (ciudad) values ("MANGUERA AZUL");
    insert into ciudad (ciudad) values ("POLANCO");
    insert into ciudad (ciudad) values ("POLANCO SUR");
    insert into ciudad (ciudad) values ("PUNTAS DE POLANCO");
    insert into ciudad (ciudad) values ("CHAMAME");
    insert into ciudad (ciudad) values ("ESPUELITAS");
    insert into ciudad (ciudad) values ("SIERRAS BLANCAS");
    insert into ciudad (ciudad) values ("LA CUCHILLA");
    insert into ciudad (ciudad) values ("COSTAS DEL SOLDADO");
    insert into ciudad (ciudad) values ("CASUPA CHICO");
    insert into ciudad (ciudad) values ("PUNTAS DE SANTA LUCIA");
    insert into ciudad (ciudad) values ("ARROYO DEL MEDIO");
    insert into ciudad (ciudad) values ("COSTA DEL LENGUAZO");
    insert into ciudad (ciudad) values ("EL SOLDADO");
    insert into ciudad (ciudad) values ("PUNTAS DEL PERDIDO");
    insert into ciudad (ciudad) values ("EL ALTO");
    insert into ciudad (ciudad) values ("ORTIZ CASTRO");
    insert into ciudad (ciudad) values ("ESTACION ORTIZ");
    insert into ciudad (ciudad) values ("ORTIZ");
    insert into ciudad (ciudad) values ("HIGUERITAS");
    insert into ciudad (ciudad) values ("CAMPANERO");
    insert into ciudad (ciudad) values ("VERDUN");
    insert into ciudad (ciudad) values ("CANTERAS DEL VERDUN");
    insert into ciudad (ciudad) values ("AREQUITA");
    insert into ciudad (ciudad) values ("EL PERDIDO");
    insert into ciudad (ciudad) values ("SANTA LUCIA");
    insert into ciudad (ciudad) values ("SOLDADO");
    insert into ciudad (ciudad) values ("LA PLATA");
    insert into ciudad (ciudad) values ("PUNTAS DE LOS CHANCHOS");
    insert into ciudad (ciudad) values ("VELAZQUEZ");
    insert into ciudad (ciudad) values ("PUNTAS DE SAN FRANCISCO");
    insert into ciudad (ciudad) values ("ABRA DE ZABALETA");
    insert into ciudad (ciudad) values ("AGUAS BLANCAS");
    insert into ciudad (ciudad) values ("CASUPA");
    insert into ciudad (ciudad) values ("EL TIGRE");
    insert into ciudad (ciudad) values ("VEJIGAS");
    insert into ciudad (ciudad) values ("ROLDAN");
    insert into ciudad (ciudad) values ("PUNTAS DE VEJIGAS");
    insert into ciudad (ciudad) values ("PUNTAS DE SOLIS");
    insert into ciudad (ciudad) values ("ARROYO DE LOS PATOS");
    insert into ciudad (ciudad) values ("OMBUES DE BENTANCOR");
    insert into ciudad (ciudad) values ("BARRA DE LOS CHANCHOS");
    insert into ciudad (ciudad) values ("BARRANCAS");
    insert into ciudad (ciudad) values ("VALLE DE SOLIS");
    insert into ciudad (ciudad) values ("SOLIS");
    insert into ciudad (ciudad) values ("SOLIS GRANDE");
    insert into ciudad (ciudad) values ("ESTACION ANDREONI");
    insert into ciudad (ciudad) values ("PASO ARBELO");
    insert into ciudad (ciudad) values ("ARROYO MONZON");
    insert into ciudad (ciudad) values ("PUEBLO DE LOS MOROCHOS");
    insert into ciudad (ciudad) values ("MOLLES DEL PESCADO");
    insert into ciudad (ciudad) values ("LA VICTORIA");
    insert into ciudad (ciudad) values ("PUNTAS DE ILLESCAS");
    insert into ciudad (ciudad) values ("ARRAYAN");
    insert into ciudad (ciudad) values ("PASO REAL DE MANSAVILLAGRA");
    insert into ciudad (ciudad) values ("PUNTAS DE MANSAVILLAGRA");
    insert into ciudad (ciudad) values ("PUNTAS DE CHAMAME");
    insert into ciudad (ciudad) values ("LA PALMA");
    insert into ciudad (ciudad) values ("TABARE");
    insert into ciudad (ciudad) values ("RINCON SAUCE DEL YI");
    insert into ciudad (ciudad) values ("COSTA DE ILLESCAS");
    insert into ciudad (ciudad) values ("BARRA SAUCE DE MANSAVILLAGRA");
    insert into ciudad (ciudad) values ("SANTA CLARA");
    insert into ciudad (ciudad) values ("CHILCAS");
    insert into ciudad (ciudad) values ("LAS CHILCAS");
    insert into ciudad (ciudad) values ("CHINGOLAS");
    insert into ciudad (ciudad) values ("MANSAVILLAGRA");
    insert into ciudad (ciudad) values ("ARTEAGA");
    insert into ciudad (ciudad) values ("SAN PEDRO DE TIMOTE");
    insert into ciudad (ciudad) values ("PIEDRA CAMPANA");
    insert into ciudad (ciudad) values ("PUNTAS DE CHAMIZO");
    insert into ciudad (ciudad) values ("PUNTAS DE LA ESCOBILLA");
    insert into ciudad (ciudad) values ("COSTAS DEL AMARILLO");
    insert into ciudad (ciudad) values ("VIGNOLI");
    insert into ciudad (ciudad) values ("ARROYO LATORRE");
    insert into ciudad (ciudad) values ("ARROYO CHAMIZO");
    insert into ciudad (ciudad) values ("LA ESCOBILLA");
    insert into ciudad (ciudad) values ("PUNTAS DEL ARROYO LATORRE");
    insert into ciudad (ciudad) values ("COSTAS DEL SANTA LUCIA GRANDE");
    insert into ciudad (ciudad) values ("BARRA MOLLES DEL TIMOTE");
    insert into ciudad (ciudad) values ("COSTA DEL TALA");
    insert into ciudad (ciudad) values ("TALA DE CASTRO");
    insert into ciudad (ciudad) values ("DR. A. GALLINAL");
    insert into ciudad (ciudad) values ("MOLLES DEL TIMOTE");
    insert into ciudad (ciudad) values ("HERNANDARIAS");
    insert into ciudad (ciudad) values ("ESTACION PALERMO");
    insert into ciudad (ciudad) values ("PALERMO");
    insert into ciudad (ciudad) values ("PANTANOSO DE CASTRO");
    insert into ciudad (ciudad) values ("COLONIA ITALIA");
    insert into ciudad (ciudad) values ("ARROYO DE LOS NEGROS");
    insert into ciudad (ciudad) values ("TORNERO");
    insert into ciudad (ciudad) values ("SAN GERONIMO");
    insert into ciudad (ciudad) values ("TALITA");
    insert into ciudad (ciudad) values ("COSTA DE LA CRUZ");
    insert into ciudad (ciudad) values ("URIOSTE");
    insert into ciudad (ciudad) values ("COLONIA SANCHEZ");
    insert into ciudad (ciudad) values ("CERROS DE FLORIDA");
    insert into ciudad (ciudad) values ("SAN JUAN");
    insert into ciudad (ciudad) values ("COSTAS DE ARIAS");
    insert into ciudad (ciudad) values ("COSTAS DE CHAMIZO GRANDE");
    insert into ciudad (ciudad) values ("LAS PIEDRITAS");
    insert into ciudad (ciudad) values ("COSTA DE ARIAS");
    insert into ciudad (ciudad) values ("CHAMIZO CHICO");
    insert into ciudad (ciudad) values ("COSTAS DE CHAMIZO");
    insert into ciudad (ciudad) values ("RINCON DE LOS CAMILOS");
    insert into ciudad (ciudad) values ("SAUCE DE VILLANUEVA");
    insert into ciudad (ciudad) values ("CALLERI");
    insert into ciudad (ciudad) values ("COSTAS DE MACIEL");
    insert into ciudad (ciudad) values ("TALA DE MACIEL");
    insert into ciudad (ciudad) values ("LA CIMBRA");
    insert into ciudad (ciudad) values ("PIEDRAS COLORADAS");
    insert into ciudad (ciudad) values ("COSTA DE PARANA");
    insert into ciudad (ciudad) values ("PUNTAS DE SARANDI");
    insert into ciudad (ciudad) values ("CUCHILLA SANTO DOMINGO");
    insert into ciudad (ciudad) values ("VILLA HIPICA");
    insert into ciudad (ciudad) values ("SAUCE DE MACIEL");
    insert into ciudad (ciudad) values ("PUNTAS DE SAUCE DE MACIEL");
    insert into ciudad (ciudad) values ("CORRAL DE PIEDRA");
    insert into ciudad (ciudad) values ("CERRO DE LA MACANA");
    insert into ciudad (ciudad) values ("SANTA TERESA");
    insert into ciudad (ciudad) values ("VILLA VIEJA");
    insert into ciudad (ciudad) values ("COSTAS DEL PINTADO");
    insert into ciudad (ciudad) values ("PUNTAS DE CALLEROS");
    insert into ciudad (ciudad) values ("CHACRAS DE FLORIDA");
    insert into ciudad (ciudad) values ("JUNCAL");
    insert into ciudad (ciudad) values ("CHACRAS DEL PINTADO");
    insert into ciudad (ciudad) values ("PASO VELA");
    insert into ciudad (ciudad) values ("PASO DE LOS NOVILLOS");
    insert into ciudad (ciudad) values ("CANDIL");
    insert into ciudad (ciudad) values ("PASO CALLEROS");
    insert into ciudad (ciudad) values ("COSTAS DE SANTA LUCIA CHICO");
    insert into ciudad (ciudad) values ("RINCON DE VIGNOLI");
    insert into ciudad (ciudad) values ("ARROYO PELADO");
    insert into ciudad (ciudad) values ("PUENTE DE MENDOZA");
    insert into ciudad (ciudad) values ("AHOGADOS");
    insert into ciudad (ciudad) values ("PUNTAS DEL CORRAL DE PIEDRA");
    insert into ciudad (ciudad) values ("LA CORDOBESA");
    insert into ciudad (ciudad) values ("CUCHILLA DE VILLASBOAS");
    insert into ciudad (ciudad) values ("CHACRAS");
    insert into ciudad (ciudad) values ("CHACRAS DE BORGHI");
    insert into ciudad (ciudad) values ("VILLASBOAS");
    insert into ciudad (ciudad) values ("PUNTAS DE CHAMANGA");
    insert into ciudad (ciudad) values ("FERRIZO");
    insert into ciudad (ciudad) values ("TALAS DE MACIEL");
    insert into ciudad (ciudad) values ("COSTAS DE SAN JOSE");
    insert into ciudad (ciudad) values ("PUEBLO PINTOS");
    insert into ciudad (ciudad) values ("SAN GREGORIO DE FLORES");
    insert into ciudad (ciudad) values ("COSTAS DEL TALA");
    insert into ciudad (ciudad) values ("EL CORONILLA");
    insert into ciudad (ciudad) values ("MARINCHO");
    insert into ciudad (ciudad) values ("RINCON DEL PALACIO");
    insert into ciudad (ciudad) values ("EL TOTORAL");
    insert into ciudad (ciudad) values ("ARENAL GRANDE");
    insert into ciudad (ciudad) values ("COLONIA ALEMANA");
    insert into ciudad (ciudad) values ("PUNTAS DE MARINCHO");
    insert into ciudad (ciudad) values ("SARANDI");
    insert into ciudad (ciudad) values ("ARENAL CHICO");
    insert into ciudad (ciudad) values ("PUNTAS DE SARANDI");
    insert into ciudad (ciudad) values ("SANTA ADELAIDA");
    insert into ciudad (ciudad) values ("PUNTAS DEL SAUCE");
    insert into ciudad (ciudad) values ("LA GUARDIA");
    insert into ciudad (ciudad) values ("LA ALIANZA");
    insert into ciudad (ciudad) values ("PUNTAS DE SAN JOSE");
    insert into ciudad (ciudad) values ("VILLA PASTORA");
    insert into ciudad (ciudad) values ("PASO  DE LUGO");
    insert into ciudad (ciudad) values ("PASO HONDO");
    insert into ciudad (ciudad) values ("PASO DE MAS");
    insert into ciudad (ciudad) values ("CUCHILLA SECA");
    insert into ciudad (ciudad) values ("ARROYO DE LA VIRGEN");
    insert into ciudad (ciudad) values ("PUNTAS DE CAGANCHA");
    insert into ciudad (ciudad) values ("CUCHILLA DEL VICHADERO");
    insert into ciudad (ciudad) values ("RINCON DE ALBANO");
    insert into ciudad (ciudad) values ("PASO BELASTIQUI");
    insert into ciudad (ciudad) values ("COLONIA WILSON");
    insert into ciudad (ciudad) values ("TROPAS VIEJAS");
    insert into ciudad (ciudad) values ("PUNTAS DE CHAMIZO");
    insert into ciudad (ciudad) values ("MUNDO AZUL");
    insert into ciudad (ciudad) values ("MUNDO AZUL AGUIRRE");
    insert into ciudad (ciudad) values ("FAJARDO");
    insert into ciudad (ciudad) values ("CHAMIZO");
    insert into ciudad (ciudad) values ("PASO DEL REY");
    insert into ciudad (ciudad) values ("COSTAS DEL SAUCE");
    insert into ciudad (ciudad) values ("CORONILLA");
    insert into ciudad (ciudad) values ("TABAREZ");
    insert into ciudad (ciudad) values ("FAJINA");
    insert into ciudad (ciudad) values ("LA CASILLA");
    insert into ciudad (ciudad) values ("LAUREL");
    insert into ciudad (ciudad) values ("PASO DEL CARRETON");
    insert into ciudad (ciudad) values ("ARROYO LLANO");
    insert into ciudad (ciudad) values ("PACHINA");
    insert into ciudad (ciudad) values ("JESUS MARIA");
    insert into ciudad (ciudad) values ("PANTA");
    insert into ciudad (ciudad) values ("CRUZ DE LOS CAMINOS");
    insert into ciudad (ciudad) values ("PASO DE CAMES");
    insert into ciudad (ciudad) values ("RINCON DE ARIAS");
    insert into ciudad (ciudad) values ("CAGANCHA CHICO");
    insert into ciudad (ciudad) values ("TRANQUERA COLORADA");
    insert into ciudad (ciudad) values ("PERICO PEREZ");
    insert into ciudad (ciudad) values ("LA CUCHILLA");
    insert into ciudad (ciudad) values ("ZANJA HONDA");
    insert into ciudad (ciudad) values ("ROCHO");
    insert into ciudad (ciudad) values ("PUNTAS DE LAUREL");
    insert into ciudad (ciudad) values ("JUNCAL");
    insert into ciudad (ciudad) values ("CAGANCHA");
    insert into ciudad (ciudad) values ("RINCON DE LA TORRE");
    insert into ciudad (ciudad) values ("MINUANO Y SAUCE");
    insert into ciudad (ciudad) values ("TALA DE PEREIRA");
    insert into ciudad (ciudad) values ("PUNTAS DE GREGORIO");
    insert into ciudad (ciudad) values ("VALDEZ CHICO");
    insert into ciudad (ciudad) values ("SAUCE");
    insert into ciudad (ciudad) values ("SAUCE CHICO");
    insert into ciudad (ciudad) values ("COLONIA JUAN MARIA PEREZ");
    insert into ciudad (ciudad) values ("COSTA DEL MAURICIO");
    insert into ciudad (ciudad) values ("RINCON DE BUSCHENTAL");
    insert into ciudad (ciudad) values ("ORILLAS DEL PLATA");
    insert into ciudad (ciudad) values ("PUNTAS DE TROPA VIEJA");
    insert into ciudad (ciudad) values ("PASO DEL GUAYCURU");
    insert into ciudad (ciudad) values ("GUAYCURU");
    insert into ciudad (ciudad) values ("MAHOMA");
    insert into ciudad (ciudad) values ("PANTANOSO");
    insert into ciudad (ciudad) values ("COLONIA AMERICA");
    insert into ciudad (ciudad) values ("ESCUDERO");
    insert into ciudad (ciudad) values ("BELLA VISTA");
    insert into ciudad (ciudad) values ("PAVON");
    insert into ciudad (ciudad) values ("PICADA GAMBETTA");
    insert into ciudad (ciudad) values ("RINCON DE CUFRE");
    insert into ciudad (ciudad) values ("RINCON DE ARAZATI");
    insert into ciudad (ciudad) values ("COLONIA SAN JOAQUIN");
    insert into ciudad (ciudad) values ("PASO DE LAS PIEDRAS");
    insert into ciudad (ciudad) values ("COSTA DE ROSARIO");
    insert into ciudad (ciudad) values ("PASO DE LA QUINTA");
    insert into ciudad (ciudad) values ("CERROS NEGROS");
    insert into ciudad (ciudad) values ("BARRANCAS COLORADAS");
    insert into ciudad (ciudad) values ("CONCORDIA");
    insert into ciudad (ciudad) values ("COLONIA QUEVEDO");
    insert into ciudad (ciudad) values ("RESGUARDO CUFRE");
    insert into ciudad (ciudad) values ("BARRIO OLIMPICO");
    insert into ciudad (ciudad) values ("COLONIA ESPAOLA");
    insert into ciudad (ciudad) values ("COSTAS DE SAN JUAN");
    insert into ciudad (ciudad) values ("PUNTAS DE SAN JUAN");
    insert into ciudad (ciudad) values ("LAS CHISPAS");
    insert into ciudad (ciudad) values ("PASO BIRRIEL");
    insert into ciudad (ciudad) values ("PIEDRA CHATA");
    insert into ciudad (ciudad) values ("ZUNIN");
    insert into ciudad (ciudad) values ("COSTAS DE POLONIA");
    insert into ciudad (ciudad) values ("TRES ESQUINAS");
    insert into ciudad (ciudad) values ("MANANTIALES");
    insert into ciudad (ciudad) values ("TERMINAL");
    insert into ciudad (ciudad) values ("MEDIA AGUA");
    insert into ciudad (ciudad) values ("PASO MORLAN");
    insert into ciudad (ciudad) values ("PUNTAS DEL SAUCE");
    insert into ciudad (ciudad) values ("PUNTAS DE MELO");
    insert into ciudad (ciudad) values ("BARKER NORTE");
    insert into ciudad (ciudad) values ("COSTA DE COLLA AL ESTE");
    insert into ciudad (ciudad) values ("COSTA DEL NAVARRO");
    insert into ciudad (ciudad) values ("ROSARIO Y COLLA");
    insert into ciudad (ciudad) values ("COLONIA TALICE");
    insert into ciudad (ciudad) values ("COLONIA PEIRANO");
    insert into ciudad (ciudad) values ("PICADA DE BENITEZ");
    insert into ciudad (ciudad) values ("PUERTO ROSARIO");
    insert into ciudad (ciudad) values ("PUERTO CONCORDIA");
    insert into ciudad (ciudad) values ("RADIAL ROSARIO");
    insert into ciudad (ciudad) values ("PASO QUICHO");
    insert into ciudad (ciudad) values ("TOMAS BELL");
    insert into ciudad (ciudad) values ("VILLA PANCHA");
    insert into ciudad (ciudad) values ("RINCON DEL REY");
    insert into ciudad (ciudad) values ("BONJOUR");
    insert into ciudad (ciudad) values ("PIEDRAS BLANCAS");
    insert into ciudad (ciudad) values ("COLONIA SARANDI");
    insert into ciudad (ciudad) values ("MOLLES DE MIGUELETE");
    insert into ciudad (ciudad) values ("MIGUELETE DE CONCHILLAS");
    insert into ciudad (ciudad) values ("PUNTAS DE JUAN GONZALEZ");
    insert into ciudad (ciudad) values ("EL CUADRO");
    insert into ciudad (ciudad) values ("CERRO DE LAS ARMAS");
    insert into ciudad (ciudad) values ("PASO HOSPITAL");
    insert into ciudad (ciudad) values ("PASO HOSPITAL MANANTIALES");
    insert into ciudad (ciudad) values ("SAN LUIS SANCHEZ");
    insert into ciudad (ciudad) values ("MINAS DE NARANCIO");
    insert into ciudad (ciudad) values ("PATITAS");
    insert into ciudad (ciudad) values ("ESTACION ESTANZUELA");
    insert into ciudad (ciudad) values ("ESTACION EXPERIMENTAL \"LA ESTANZUELA\"");
    insert into ciudad (ciudad) values ("SAN PEDRO NORTE");
    insert into ciudad (ciudad) values ("PUNTAS DE SAN PEDRO");
    insert into ciudad (ciudad) values ("SAN PEDRO DE ARRIBA");
    insert into ciudad (ciudad) values ("PIEDRA DE LOS INDIOS");
    insert into ciudad (ciudad) values ("REDUCTO");
    insert into ciudad (ciudad) values ("QUINTON");
    insert into ciudad (ciudad) values ("PUNTAS DEL RIACHUELO");
    insert into ciudad (ciudad) values ("COSTA DE TARARIRAS");
    insert into ciudad (ciudad) values ("SAN LUIS DE TARARIRAS");
    insert into ciudad (ciudad) values ("SAN LUIS");
    insert into ciudad (ciudad) values ("SAN JUAN");
    insert into ciudad (ciudad) values ("PUERTO PLATERO");
    insert into ciudad (ciudad) values ("POLANCO");
    insert into ciudad (ciudad) values ("POLANCOS");
    insert into ciudad (ciudad) values ("LAS FLORES");
    insert into ciudad (ciudad) values ("EL CHILENO");
    insert into ciudad (ciudad) values ("VIBORAS Y VACAS");
    insert into ciudad (ciudad) values ("VIBORAS");
    insert into ciudad (ciudad) values ("COLONIA ARRUE");
    insert into ciudad (ciudad) values ("COSTA DE VACAS");
    insert into ciudad (ciudad) values ("COLONIA ESTRELLA");
    insert into ciudad (ciudad) values ("COSTAS DE JUAN GONZALEZ");
    insert into ciudad (ciudad) values ("JUAN GONZALEZ");
    insert into ciudad (ciudad) values ("SAN ROQUE");
    insert into ciudad (ciudad) values ("SARANDI CAMPANA");
    insert into ciudad (ciudad) values ("SANTA ROSA");
    insert into ciudad (ciudad) values ("MARTIN CHICO DE CONCHILLAS");
    insert into ciudad (ciudad) values ("BUENA HORA");
    insert into ciudad (ciudad) values ("MARTIN CHICO");
    insert into ciudad (ciudad) values ("PUNTA FRANCESA");
    insert into ciudad (ciudad) values ("BELGRANO NORTE");
    insert into ciudad (ciudad) values ("BELGRANO SUR");
    insert into ciudad (ciudad) values ("ARROYO GRANDE");
    insert into ciudad (ciudad) values ("MONZON");
    insert into ciudad (ciudad) values ("CERRO VERA");
    insert into ciudad (ciudad) values ("PROGRESO");
    insert into ciudad (ciudad) values ("PUNTAS DEL TALA");
    insert into ciudad (ciudad) values ("LA LAGUNA");
    insert into ciudad (ciudad) values ("DURAZNITO");
    insert into ciudad (ciudad) values ("COLONIA SANTA CLARA");
    insert into ciudad (ciudad) values ("COSTAS DEL PERDIDO");
    insert into ciudad (ciudad) values ("PUNTAS DE DURAZNO");
    insert into ciudad (ciudad) values ("PARADA SUAREZ");
    insert into ciudad (ciudad) values ("BAJOS DEL PERDIDO");
    insert into ciudad (ciudad) values ("ALTOS DEL PERDIDO");
    insert into ciudad (ciudad) values ("ZANJA HONDA");
    insert into ciudad (ciudad) values ("CUEVA DEL TIGRE");
    insert into ciudad (ciudad) values ("PUNTAS DE SAN SALVADOR");
    insert into ciudad (ciudad) values ("LATA DEL PERDIDO");
    insert into ciudad (ciudad) values ("RINCON DE COLOLO");
    insert into ciudad (ciudad) values ("SAN DIOS");
    insert into ciudad (ciudad) values ("UNIDAD COOPERARIA No 1");
    insert into ciudad (ciudad) values ("LA TABLA");
    insert into ciudad (ciudad) values ("COLOLO");
    insert into ciudad (ciudad) values ("SARANDI CHICO");
    insert into ciudad (ciudad) values ("GRITO DE ASENCIO");
    insert into ciudad (ciudad) values ("GARULA");
    insert into ciudad (ciudad) values ("COQUIMBO");
    insert into ciudad (ciudad) values ("PEDRO CHICO");
    insert into ciudad (ciudad) values ("EL AGUILA");
    insert into ciudad (ciudad) values ("OLIVERA");
    insert into ciudad (ciudad) values ("COLONIA URUGUAYA");
    insert into ciudad (ciudad) values ("CORRALITO");
    insert into ciudad (ciudad) values ("CUCHILLA DEL CORRALITO");
    insert into ciudad (ciudad) values ("MACIEL");
    insert into ciudad (ciudad) values ("SAN MARTIN");
    insert into ciudad (ciudad) values ("ARROYO DEL MEDIO");
    insert into ciudad (ciudad) values ("BEQUELO");
    insert into ciudad (ciudad) values ("SANTA BLANCA");
    insert into ciudad (ciudad) values ("CHACRAS DE MERCEDES");
    insert into ciudad (ciudad) values ("ASENCIO");
    insert into ciudad (ciudad) values ("COLONIA DIAZ");
    insert into ciudad (ciudad) values ("CERRO ALEGRE");
    insert into ciudad (ciudad) values ("LAS MAULAS");
    insert into ciudad (ciudad) values ("BIZCOCHO");
    insert into ciudad (ciudad) values ("ESPINILLO");
    insert into ciudad (ciudad) values ("PASO DE LA ARENA");
    insert into ciudad (ciudad) values ("PASO DE RAMOS");
    insert into ciudad (ciudad) values ("COSTA DEL AGUILA");
    insert into ciudad (ciudad) values ("CUATRO BOCAS DE BUENA VISTA");
    insert into ciudad (ciudad) values ("ARENAL CHICO");
    insert into ciudad (ciudad) values ("PUNTAS DE ARENALES");
    insert into ciudad (ciudad) values ("LA PALMA");
    insert into ciudad (ciudad) values ("CAADA PARAGUAYA");
    insert into ciudad (ciudad) values ("BUENA VISTA");
    insert into ciudad (ciudad) values ("VILLA ALEJANDRINA");
    insert into ciudad (ciudad) values ("PUNTAS DE AVERIAS");
    insert into ciudad (ciudad) values ("SANTA ROSA");
    insert into ciudad (ciudad) values ("ESTACION FRANCIA");
    insert into ciudad (ciudad) values ("LA CORONILLA");
    insert into ciudad (ciudad) values ("PASO DE SOCA");
    insert into ciudad (ciudad) values ("LA PALMA");
    insert into ciudad (ciudad) values ("PALMAR GRANDE");
    insert into ciudad (ciudad) values ("SARANDI");
    insert into ciudad (ciudad) values ("ROLON");
    insert into ciudad (ciudad) values ("PASO DE BALBUENA");
    insert into ciudad (ciudad) values ("PAURU");
    insert into ciudad (ciudad) values ("EL PROGRESO");
    insert into ciudad (ciudad) values ("LAS FLORES");
    insert into ciudad (ciudad) values ("MOLLES DE PORRUA");
    insert into ciudad (ciudad) values ("EL SURCO");
    insert into ciudad (ciudad) values ("LA ARENA");
    insert into ciudad (ciudad) values ("PASO RAMIREZ");
    insert into ciudad (ciudad) values ("VALLE DE SOBA");
    insert into ciudad (ciudad) values ("PASO DE LEOPOLDO");
    insert into ciudad (ciudad) values ("DON ESTEBAN");
    insert into ciudad (ciudad) values ("MATAOJO");
    insert into ciudad (ciudad) values ("SANTA ISABEL");
    insert into ciudad (ciudad) values ("PASO DE LOS COBRES");
    insert into ciudad (ciudad) values ("ULESTE");
    insert into ciudad (ciudad) values ("LA FLORIDA");
    insert into ciudad (ciudad) values ("ARROYO NEGRO");
    insert into ciudad (ciudad) values ("TRES BOCAS");
    insert into ciudad (ciudad) values ("SANCHEZ");
    insert into ciudad (ciudad) values ("LA UNION");
    insert into ciudad (ciudad) values ("SANCHEZ CHICO");
    insert into ciudad (ciudad) values ("SAUCE");
    insert into ciudad (ciudad) values ("ESTANCIA VICHADERO");
    insert into ciudad (ciudad) values ("EL ABROJAL");
    insert into ciudad (ciudad) values ("SANTA ELISA");
    insert into ciudad (ciudad) values ("SAN LORENZO");
    insert into ciudad (ciudad) values ("YAGUARETE");
    insert into ciudad (ciudad) values ("OMBUCITOS");
    insert into ciudad (ciudad) values ("LAS FRACCIONES");
    insert into ciudad (ciudad) values ("LAS MARGARITAS");
    insert into ciudad (ciudad) values ("CARACOLES");
    insert into ciudad (ciudad) values ("LOS RANCHOS");
    insert into ciudad (ciudad) values ("COLONIA JUNCAL");
    insert into ciudad (ciudad) values ("PERICO MORENO");
    insert into ciudad (ciudad) values ("TRES BOCAS");
    insert into ciudad (ciudad) values ("PUNTAS DE BURICAYUPI");
    insert into ciudad (ciudad) values ("GUALEGUAY");
    insert into ciudad (ciudad) values ("PUNTAS DE GUALEGUAY");
    insert into ciudad (ciudad) values ("SAUCE DEL BURICAYUPI");
    insert into ciudad (ciudad) values ("EL CHACO");
    insert into ciudad (ciudad) values ("EL HORNO");
    insert into ciudad (ciudad) values ("PASO DE LOS CARROS");
    insert into ciudad (ciudad) values ("EL TARUGO");
    insert into ciudad (ciudad) values ("QUEGUAY GRANDE");
    insert into ciudad (ciudad) values ("COLONIA URUGUAYA");
    insert into ciudad (ciudad) values ("GUAYABOS");
    insert into ciudad (ciudad) values ("PARADA PANDULE");
    insert into ciudad (ciudad) values ("EL DURAZNAL");
    insert into ciudad (ciudad) values ("PUNTAS DE BACACUA");
    insert into ciudad (ciudad) values ("LAS FLORES");
    insert into ciudad (ciudad) values ("ARROYO NEGRO");
    insert into ciudad (ciudad) values ("TOMAS PAZ");
    insert into ciudad (ciudad) values ("SAN MAURICIO");
    insert into ciudad (ciudad) values ("RINCON DEL INDIO");
    insert into ciudad (ciudad) values ("PARADA DAYMAN");
    insert into ciudad (ciudad) values ("GUAYUVIRA");
    insert into ciudad (ciudad) values ("GUYUBIRA");
    insert into ciudad (ciudad) values ("PARADA RIVAS");
    insert into ciudad (ciudad) values ("COLONIA SANTA BLANCA");
    insert into ciudad (ciudad) values ("SANTA KILDA");
    insert into ciudad (ciudad) values ("CARUMBE");
    insert into ciudad (ciudad) values ("PALMAR DEL QUEBRACHO");
    insert into ciudad (ciudad) values ("GUAVIYU DE QUEBRACHO");
    insert into ciudad (ciudad) values ("SAUCE DEL QUEGUAY");
    insert into ciudad (ciudad) values ("SAUCE DE ABAJO");
    insert into ciudad (ciudad) values ("VALDIVIA");
    insert into ciudad (ciudad) values ("PUNTAS DE LAS ISLETAS");
    insert into ciudad (ciudad) values ("ETCHEMENDI");
    insert into ciudad (ciudad) values ("VALDEZ");
    insert into ciudad (ciudad) values ("ARROYO MALO");
    insert into ciudad (ciudad) values ("COLONIA ARROYO MALO");
    insert into ciudad (ciudad) values ("PUNTAS DE CANGUE");
    insert into ciudad (ciudad) values ("LAS PALMAS");
    insert into ciudad (ciudad) values ("COSTA DE SACRA");
    insert into ciudad (ciudad) values ("SAN FRANCISCO");
    insert into ciudad (ciudad) values ("COLONIA PAYSANDU");
    insert into ciudad (ciudad) values ("COLONIA CANGUE");
    insert into ciudad (ciudad) values ("SAN MIGUEL");
    insert into ciudad (ciudad) values ("RABON");
    insert into ciudad (ciudad) values ("CORRAL DE PIEDRA");
    insert into ciudad (ciudad) values ("LOS ORIENTALES");
    insert into ciudad (ciudad) values ("ZANJA DEL TIGRE");
    insert into ciudad (ciudad) values ("CERRO CHATO");
    insert into ciudad (ciudad) values ("TORO NEGRO");
    insert into ciudad (ciudad) values ("PASO DEL POTRERO");
    insert into ciudad (ciudad) values ("CARUMBE");
    insert into ciudad (ciudad) values ("CERRILLADA");
    insert into ciudad (ciudad) values ("PASO DEL TAPADO");
    insert into ciudad (ciudad) values ("BORDENAVE");
    insert into ciudad (ciudad) values ("PASO NUEVO DEL ARAPEY");
    insert into ciudad (ciudad) values ("MATAOJO GRANDE");
    insert into ciudad (ciudad) values ("FERREIRA");
    insert into ciudad (ciudad) values ("LA BOLSA 03");
    insert into ciudad (ciudad) values ("ZANJA DE ALCAIN");
    insert into ciudad (ciudad) values ("VALENTIN GRANDE");
    insert into ciudad (ciudad) values ("LA BOLSA 02");
    insert into ciudad (ciudad) values ("PASO FIALHO");
    insert into ciudad (ciudad) values ("SAUCE CHICO");
    insert into ciudad (ciudad) values ("EL MELLADO");
    insert into ciudad (ciudad) values ("PIEDRA PINTADA");
    insert into ciudad (ciudad) values ("PUEBLO FARIAS");
    insert into ciudad (ciudad) values ("CERRILLADAS DE SAUCEDO");
    insert into ciudad (ciudad) values ("TALAS DE ITAPEBI");
    insert into ciudad (ciudad) values ("LA VITICOLA");
    insert into ciudad (ciudad) values ("TROPIEZO");
    insert into ciudad (ciudad) values ("PARADA HERRERIA");
    insert into ciudad (ciudad) values ("TROPEZON");
    insert into ciudad (ciudad) values ("EL ESPINILLAR");
    insert into ciudad (ciudad) values ("CHACRAS DE CONSTITUCION");
    insert into ciudad (ciudad) values ("ITAPEBI");
    insert into ciudad (ciudad) values ("NUEVA HESPERIDES");
    insert into ciudad (ciudad) values ("CORRALITO");
    insert into ciudad (ciudad) values ("CHIFLERO");
    insert into ciudad (ciudad) values ("PINTADO");
    insert into ciudad (ciudad) values ("COLONIA PINTADO");
    insert into ciudad (ciudad) values ("ESTIBA");
    insert into ciudad (ciudad) values ("TAMANDUA");
    insert into ciudad (ciudad) values ("PINTADO GRANDE");
    insert into ciudad (ciudad) values ("CATALAN VOLCAN");
    insert into ciudad (ciudad) values ("CATALAN GRANDE");
    insert into ciudad (ciudad) values ("MENESES");
    insert into ciudad (ciudad) values ("PASO DE RAMOS");
    insert into ciudad (ciudad) values ("TARUMAN");
    insert into ciudad (ciudad) values ("ZANJA ARUERA");
    insert into ciudad (ciudad) values ("SARANDI DE CUARO");
    insert into ciudad (ciudad) values ("PAGUERO");
    insert into ciudad (ciudad) values ("FAGUNDEZ");
    insert into ciudad (ciudad) values ("PASO DE LEON");
    insert into ciudad (ciudad) values ("CERRITO");
    insert into ciudad (ciudad) values ("COLONIA ESTRELLA");
    insert into ciudad (ciudad) values ("PALMA SOLA");
    insert into ciudad (ciudad) values ("LENGUAZO");
    insert into ciudad (ciudad) values ("SARANDI DE YACUY");
    insert into ciudad (ciudad) values ("PAREDON");
    insert into ciudad (ciudad) values ("VILLA JUANITA");
    insert into ciudad (ciudad) values ("EL CEIBO");
    insert into ciudad (ciudad) values ("PASO DE FRONTERA");
    insert into ciudad (ciudad) values ("PASO DEL PUERTO");
    insert into ciudad (ciudad) values ("EL PALMITO");
    insert into ciudad (ciudad) values ("ZANJA HONDA");
    insert into ciudad (ciudad) values ("PASO DE ARRIERA");
    insert into ciudad (ciudad) values ("PUEBLO DE LOS SANTOS");
    insert into ciudad (ciudad) values ("LA CHILCA");
    insert into ciudad (ciudad) values ("VILLA INDART");
    insert into ciudad (ciudad) values ("CRUZ DE SAN PEDRO");
    insert into ciudad (ciudad) values ("YAGUARI");
    insert into ciudad (ciudad) values ("GUAVIYU");
    insert into ciudad (ciudad) values ("LA CAILLAVA");
    insert into ciudad (ciudad) values ("RINCON DE RODRIGUEZ");
    insert into ciudad (ciudad) values ("RINCON DE AMARILLO");
    insert into ciudad (ciudad) values ("RINCON DE YAGUARI");
    insert into ciudad (ciudad) values ("LA CERRILLADA");
    insert into ciudad (ciudad) values ("CERROS BLANCOS");
    insert into ciudad (ciudad) values ("CHIRCA DE CARAGUATA");
    insert into ciudad (ciudad) values ("PUNTAS DE ABROJAL");
    insert into ciudad (ciudad) values ("CERRO CHATO");
    insert into ciudad (ciudad) values ("ABROJAL");
    insert into ciudad (ciudad) values ("PUEBLO SOCORRO");
    insert into ciudad (ciudad) values ("CARAGUATA");
    insert into ciudad (ciudad) values ("ALBORADA");
    insert into ciudad (ciudad) values ("CORONILLA");
    insert into ciudad (ciudad) values ("PUNTAS DEL YAGUARI");
    insert into ciudad (ciudad) values ("CUCHILLA MANGUERAS");
    insert into ciudad (ciudad) values ("TRES PUENTES");
    insert into ciudad (ciudad) values ("BERRUTI");
    insert into ciudad (ciudad) values ("SEGARRA");
    insert into ciudad (ciudad) values ("CORONILLA DE CORRALES");
    insert into ciudad (ciudad) values ("CERRO PELADO AL ESTE");
    insert into ciudad (ciudad) values ("BLANQUILLOS");
    insert into ciudad (ciudad) values ("PASO AMARILLO");
    insert into ciudad (ciudad) values ("MINAS DE ZAPUCAY");
    insert into ciudad (ciudad) values ("LAURELES");
    insert into ciudad (ciudad) values ("BUENA ORDEN AL NORTE");
    insert into ciudad (ciudad) values ("CUCHILLA DE YAGUARI");
    insert into ciudad (ciudad) values ("CURTUME");
    insert into ciudad (ciudad) values ("BATOVI");
    insert into ciudad (ciudad) values ("CAPON ALTO");
    insert into ciudad (ciudad) values ("ATAQUES");
    insert into ciudad (ciudad) values ("PASO DEL TAPADO");
    insert into ciudad (ciudad) values ("PUNTAS DE CORRALES");
    insert into ciudad (ciudad) values ("PASO DE LA CALERA");
    insert into ciudad (ciudad) values ("PASO DE GAIRE");
    insert into ciudad (ciudad) values ("RINCON DE DINIZ");
    insert into ciudad (ciudad) values ("RINCON DE ROLAND");
    insert into ciudad (ciudad) values ("SANTA ERNESTINA");
    insert into ciudad (ciudad) values ("COSTAS DE CUAPIRU");
    insert into ciudad (ciudad) values ("MINAS DE CUAPIRU (USINAS)");
    insert into ciudad (ciudad) values ("TRES CERROS");
    insert into ciudad (ciudad) values ("SAN GREGORIO");
    insert into ciudad (ciudad) values ("RINCON DE LOS CASTILLOS");
    insert into ciudad (ciudad) values ("RINCON DE TRES CERROS");
    insert into ciudad (ciudad) values ("CERRO CHAPEU");
    insert into ciudad (ciudad) values ("CERRO CAQUEIRO");
    insert into ciudad (ciudad) values ("PLATON");
    insert into ciudad (ciudad) values ("CURTICEIRAS");
    insert into ciudad (ciudad) values ("CUCHILLA DE TRES CERROS");
    insert into ciudad (ciudad) values ("PUNTAS DE CUAPIRU");
    insert into ciudad (ciudad) values ("PASO DE ATAQUES");
    insert into ciudad (ciudad) values ("LOS POTREROS");
    insert into ciudad (ciudad) values ("RINCON DE MORAES");
    insert into ciudad (ciudad) values ("PARADA MEDINA");
    insert into ciudad (ciudad) values ("CERRO SOLITO");
    insert into ciudad (ciudad) values ("OTRA CIUDAD");
