export class FacturaModel {
  constructor () {
    this.id = ''
    this.bonificacion = ''
    this.cantidad = ''
    this.codigo = ''
    this.concepto = ''
    this.condicionPagoEnum = ''
    this.domicilioComercial = ''
    this.fechaEmision = ''
    this.fechaVencimiento = ''
    this.fechaVencimientoId = ''
    this.iva = ''
    this.notas = ''
    this.numeroComprobante = ''
    this.otrosImpuestos = ''
    this.pagada = ''
    this.precioUnitario = ''
    this.razonSocial = ''
    this.remitoId = ''
    this.tipoComprobante = ''
    this.viajeId = ''

    this.creada = ''
    this.creador = ''
    this.modificada = ''
    this.modificador = ''
    this.eliminada = ''
    this.eliminador = ''
  }
}
