export class FacturaModel {
  constructor () {
    this.id = ''
    this.descuento = ''
    this.fecha = ''
    this.iva = ''
    this.numeroComprobante = ''
    this.recarga = ''
    this.subTotal = ''
    this.tipoComprobante = ''
    this.pagada = ''
    this.remito = ''
    this.comprador = ''
    this.fechaViaje = ''
    this.numeroGuia = ''
    this.origen = ''
    this.destino = ''
    this.conductor = ''
    this.camion = ''
    this.categoriaViaje = ''
    this.cantidadTransportada = ''

    this.creada = ''
    this.creador = ''
    this.modificada = ''
    this.modificador = ''
    this.eliminada = ''
    this.eliminador = ''
  }
}
