export class ViajeModel {
  constructor () {
    this.id = ''
    this.cantidadTransportada = ''
    this.valorKm = ''
    this.notas = ''
    this.categoriaViaje = ''
    this.comprador = ''
    this.destino = ''
    this.fecha = ''
    this.origen = ''
    this.guia = ''
    this.neto = ''
    this.kmCargado = ''
    this.kmVacio = ''
    this.conductor = ''
    this.camion = ''
    this.acoplado = ''
    this.carga = ''
    this.vendedor = ''
    this.intermediario = ''

    this.creada = ''
    this.creador = ''
    this.modificada = ''
    this.modificador = ''
    this.eliminada = ''
    this.eliminador = ''
  }
}
